/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/health/live': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liveness — process is up, nothing else checked. */
		get: operations['HealthLiveLive'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/ready': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Readiness — Postgres answers. */
		get: operations['HealthReadyReady'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health/queue': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Queue depth and stalled workers, without needing Logfire. */
		get: operations['HealthQueueQueue'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/river': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** A page of the river, newest first by when we first saw it. */
		get: operations['RiverRiver'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/items/{item_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** One article, with every reading held for it. */
		get: operations['ItemsItemIdArticle'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/items/{item_id}/opened': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Record that an item was opened. */
		post: operations['ItemsItemIdOpenedOpened'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/sections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** The categories a river can be sliced by. */
		get: operations['SectionsSections'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/client-reports': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Record something the reading UI could not recover from. */
		post: operations['ClientReportsClientReport'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/subscriptions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Every feed we follow, and how it is filed. */
		get: operations['SubscriptionsFollowing'];
		put?: never;
		/** Follow a feed, or a page that names one. */
		post: operations['SubscriptionsFollow'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/subscriptions/{feed_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Stop following, keeping the archive. */
		delete: operations['SubscriptionsFeedIdUnfollow'];
		options?: never;
		head?: never;
		/** File a feed under a section. */
		patch: operations['SubscriptionsFeedIdRefile'];
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** Article */
		Article: {
			/** Format: uuid */
			id: string;
			title: string;
			url: string;
			outlet: string;
			author: string;
			deck: string;
			feed_body: string;
			page_body: string;
			reading: string;
			published_at: string | null;
			/** Format: date-time */
			first_seen_at: string;
			read: boolean;
			comments_url: string;
			versions: number;
			section: string;
		};
		/** Entry */
		Entry: {
			/** Format: uuid */
			id: string;
			title: string;
			url: string;
			outlet: string;
			author: string;
			deck: string;
			published_at: string | null;
			/** Format: date-time */
			first_seen_at: string;
			read: boolean;
		};
		/** Filing */
		Filing: {
			category: string;
		};
		/** Following */
		Following: {
			/** Format: uuid */
			id: string;
			title: string;
			url: string;
			site_url: string;
			category: string;
			last_success_at: string | null;
		};
		/** NewFeed */
		NewFeed: {
			url: string;
			/** @default  */
			category: string;
		};
		/** Opened */
		Opened: {
			/** Format: date-time */
			read_at: string;
		};
		/** Report */
		Report: {
			kind: string;
			message: string;
			url: string;
			display: string;
			since_visible: number;
		};
		/** River */
		River: {
			entries: components['schemas']['Entry'][];
			cursor: string;
			updated: string | null;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	HealthLiveLive: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: string;
					};
				};
			};
		};
	};
	HealthReadyReady: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: string;
					};
				};
			};
		};
	};
	HealthQueueQueue: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: number;
					};
				};
			};
		};
	};
	RiverRiver: {
		parameters: {
			query?: {
				/** @description A subscription category; empty is all. */
				section?: string;
				/** @description The cursor a previous page ended on. */
				after?: string;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['River'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ItemsItemIdArticle: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				item_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Article'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	ItemsItemIdOpenedOpened: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				item_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Opened'];
				};
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	SectionsSections: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': string[];
				};
			};
		};
	};
	ClientReportsClientReport: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['Report'];
			};
		};
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	SubscriptionsFollowing: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, document follows */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['Following'][];
				};
			};
		};
	};
	SubscriptionsFollow: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['NewFeed'];
			};
		};
		responses: {
			/** @description Document created, URL follows */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	SubscriptionsFeedIdUnfollow: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				feed_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
	SubscriptionsFeedIdRefile: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				feed_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['Filing'];
			};
		};
		responses: {
			/** @description Request fulfilled, nothing follows */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad request syntax or unsupported method */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						status_code: number;
						detail: string;
						extra?:
							| null
							| {
									[key: string]: unknown;
							  }
							| unknown[];
					};
				};
			};
		};
	};
}
