"""The models and the migrations, checked against each other."""

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected

from old_news.config import Settings
from old_news.db.migrate import alembic_config


def test_the_models_and_the_migrations_agree(migrated: None, settings: Settings):
    """`alembic check`, which CLAUDE.md names as the safeguard and nothing was running.

    An index the models do not declare is one the next autogenerated revision quietly
    drops, and the two BM25 indexes search reads were exactly that for a while.
    """
    try:
        command.check(alembic_config(settings.database.sqlalchemy_url))
    except AutogenerateDiffsDetected as drift:
        pytest.fail(f"run `just migration` and read what comes out:\n{drift}")
