"""drop the health views

They were built before anything consumed them. Nothing in `src/` ever read one: every
definition was compiled from a hybrid property that already existed, so a view was a
second rendering of logic whose only reader was a person at a psql prompt. `explain` gives
them the same plan as the hybrid, because they were relocations rather than re-derivations
— which is what kept the two from disagreeing, and also what left them buying nothing.

The cost was the part that mattered: a view moves logic away from the call site, which is
where it has to be understood.

They come back with the screen that reads them, and that screen decides the shape — a
per-row relocation like these, or a `GROUP BY` aggregate, which would be genuinely faster
and would genuinely be a second definition.

Revision ID: 5bf73759d4d6
Revises: 7585999bead4
Create Date: 2026-08-20 11:37:00.000000+00:00

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_view import PGView

# revision identifiers, used by Alembic.
revision: str = "5bf73759d4d6"
down_revision: str | Sequence[str] | None = "7585999bead4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_feed_health = PGView(
        schema="public",
        signature="feed_health",
        definition="SELECT id AS feed_id,\n    url,\n    ( SELECT count(*) AS count_1\n           FROM feed_polls\n          WHERE ((feed_polls.feed_id = feeds.id) AND (feed_polls.outcome = 'failed'::text) AND ((( SELECT max(feed_polls_1.polled_at) AS max_1\n                   FROM feed_polls feed_polls_1\n                  WHERE ((feed_polls_1.feed_id = feeds.id) AND (feed_polls_1.outcome <> 'failed'::text))) IS NULL) OR (feed_polls.polled_at > ( SELECT max(feed_polls_1.polled_at) AS max_1\n                   FROM feed_polls feed_polls_1\n                  WHERE ((feed_polls_1.feed_id = feeds.id) AND (feed_polls_1.outcome <> 'failed'::text))))))) AS consecutive_failures,\n    (EXISTS ( SELECT feed_polls.id\n           FROM feed_polls\n          WHERE ((feed_polls.feed_id = feeds.id) AND (feed_polls.status = 410)))) AS gone,\n    ( SELECT feed_polls.outcome\n           FROM feed_polls\n          WHERE (feed_polls.feed_id = feeds.id)\n          ORDER BY feed_polls.polled_at DESC\n         LIMIT 1) AS last_outcome,\n    last_success_at,\n    next_poll_at\n   FROM feeds",
    )
    op.drop_entity(public_feed_health)

    public_host_health = PGView(
        schema="public",
        signature="host_health",
        definition="SELECT id AS host_id,\n    name,\n    ( SELECT count(*) AS count_1\n           FROM page_captures\n          WHERE ((page_captures.host_id = hosts.id) AND ((page_captures.capture_policy)::text = '2'::text) AND (page_captures.outcome = 'failed'::text) AND ((( SELECT max(page_captures_1.fetched_at) AS max_1\n                   FROM page_captures page_captures_1\n                  WHERE ((page_captures_1.host_id = hosts.id) AND ((page_captures_1.capture_policy)::text = '2'::text) AND (page_captures_1.outcome = 'ok'::text))) IS NULL) OR (page_captures.fetched_at > ( SELECT max(page_captures_1.fetched_at) AS max_1\n                   FROM page_captures page_captures_1\n                  WHERE ((page_captures_1.host_id = hosts.id) AND ((page_captures_1.capture_policy)::text = '2'::text) AND (page_captures_1.outcome = 'ok'::text))))))) AS capture_failures,\n    ( SELECT max(page_captures.fetched_at) AS max_2\n           FROM page_captures\n          WHERE ((page_captures.host_id = hosts.id) AND ((page_captures.capture_policy)::text = '2'::text) AND (page_captures.outcome = 'failed'::text) AND ((( SELECT max(page_captures_2.fetched_at) AS max_3\n                   FROM page_captures page_captures_2\n                  WHERE ((page_captures_2.host_id = hosts.id) AND ((page_captures_2.capture_policy)::text = '2'::text) AND (page_captures_2.outcome = 'ok'::text))) IS NULL) OR (page_captures.fetched_at > ( SELECT max(page_captures_2.fetched_at) AS max_3\n                   FROM page_captures page_captures_2\n                  WHERE ((page_captures_2.host_id = hosts.id) AND ((page_captures_2.capture_policy)::text = '2'::text) AND (page_captures_2.outcome = 'ok'::text))))))) AS last_capture_failure,\n    requires_www\n   FROM hosts",
    )
    op.drop_entity(public_host_health)

    public_item_reading = PGView(
        schema="public",
        signature="item_reading",
        definition="SELECT id AS item_id,\n        CASE\n            WHEN (length(COALESCE(( SELECT extractions.body\n               FROM (extractions\n                 JOIN item_versions ON ((item_versions.id = extractions.item_version_id)))\n              WHERE (item_versions.item_id = items.id)\n              ORDER BY extractions.created_at DESC, extractions.id DESC\n             LIMIT 1), ''::text)) > length(( SELECT COALESCE(NULLIF(item_versions.content, ''::text), item_versions.summary) AS coalesce_1\n               FROM item_versions\n              WHERE ((items.id = item_versions.item_id) AND (NOT (EXISTS ( SELECT successor.id\n                       FROM item_versions successor\n                      WHERE (successor.supersedes_id = item_versions.id)))))\n             LIMIT 1))) THEN COALESCE(( SELECT extractions.body\n               FROM (extractions\n                 JOIN item_versions ON ((item_versions.id = extractions.item_version_id)))\n              WHERE (item_versions.item_id = items.id)\n              ORDER BY extractions.created_at DESC, extractions.id DESC\n             LIMIT 1), ''::text)\n            ELSE ( SELECT COALESCE(NULLIF(item_versions.content, ''::text), item_versions.summary) AS coalesce_1\n               FROM item_versions\n              WHERE ((items.id = item_versions.item_id) AND (NOT (EXISTS ( SELECT successor.id\n                       FROM item_versions successor\n                      WHERE (successor.supersedes_id = item_versions.id)))))\n             LIMIT 1)\n        END AS reading_body\n   FROM items",
    )
    op.drop_entity(public_item_reading)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_item_reading = PGView(
        schema="public",
        signature="item_reading",
        definition="SELECT id AS item_id,\n        CASE\n            WHEN (length(COALESCE(( SELECT extractions.body\n               FROM (extractions\n                 JOIN item_versions ON ((item_versions.id = extractions.item_version_id)))\n              WHERE (item_versions.item_id = items.id)\n              ORDER BY extractions.created_at DESC, extractions.id DESC\n             LIMIT 1), ''::text)) > length(( SELECT COALESCE(NULLIF(item_versions.content, ''::text), item_versions.summary) AS coalesce_1\n               FROM item_versions\n              WHERE ((items.id = item_versions.item_id) AND (NOT (EXISTS ( SELECT successor.id\n                       FROM item_versions successor\n                      WHERE (successor.supersedes_id = item_versions.id)))))\n             LIMIT 1))) THEN COALESCE(( SELECT extractions.body\n               FROM (extractions\n                 JOIN item_versions ON ((item_versions.id = extractions.item_version_id)))\n              WHERE (item_versions.item_id = items.id)\n              ORDER BY extractions.created_at DESC, extractions.id DESC\n             LIMIT 1), ''::text)\n            ELSE ( SELECT COALESCE(NULLIF(item_versions.content, ''::text), item_versions.summary) AS coalesce_1\n               FROM item_versions\n              WHERE ((items.id = item_versions.item_id) AND (NOT (EXISTS ( SELECT successor.id\n                       FROM item_versions successor\n                      WHERE (successor.supersedes_id = item_versions.id)))))\n             LIMIT 1)\n        END AS reading_body\n   FROM items",
    )
    op.create_entity(public_item_reading)

    public_host_health = PGView(
        schema="public",
        signature="host_health",
        definition="SELECT id AS host_id,\n    name,\n    ( SELECT count(*) AS count_1\n           FROM page_captures\n          WHERE ((page_captures.host_id = hosts.id) AND ((page_captures.capture_policy)::text = '2'::text) AND (page_captures.outcome = 'failed'::text) AND ((( SELECT max(page_captures_1.fetched_at) AS max_1\n                   FROM page_captures page_captures_1\n                  WHERE ((page_captures_1.host_id = hosts.id) AND ((page_captures_1.capture_policy)::text = '2'::text) AND (page_captures_1.outcome = 'ok'::text))) IS NULL) OR (page_captures.fetched_at > ( SELECT max(page_captures_1.fetched_at) AS max_1\n                   FROM page_captures page_captures_1\n                  WHERE ((page_captures_1.host_id = hosts.id) AND ((page_captures_1.capture_policy)::text = '2'::text) AND (page_captures_1.outcome = 'ok'::text))))))) AS capture_failures,\n    ( SELECT max(page_captures.fetched_at) AS max_2\n           FROM page_captures\n          WHERE ((page_captures.host_id = hosts.id) AND ((page_captures.capture_policy)::text = '2'::text) AND (page_captures.outcome = 'failed'::text) AND ((( SELECT max(page_captures_2.fetched_at) AS max_3\n                   FROM page_captures page_captures_2\n                  WHERE ((page_captures_2.host_id = hosts.id) AND ((page_captures_2.capture_policy)::text = '2'::text) AND (page_captures_2.outcome = 'ok'::text))) IS NULL) OR (page_captures.fetched_at > ( SELECT max(page_captures_2.fetched_at) AS max_3\n                   FROM page_captures page_captures_2\n                  WHERE ((page_captures_2.host_id = hosts.id) AND ((page_captures_2.capture_policy)::text = '2'::text) AND (page_captures_2.outcome = 'ok'::text))))))) AS last_capture_failure,\n    requires_www\n   FROM hosts",
    )
    op.create_entity(public_host_health)

    public_feed_health = PGView(
        schema="public",
        signature="feed_health",
        definition="SELECT id AS feed_id,\n    url,\n    ( SELECT count(*) AS count_1\n           FROM feed_polls\n          WHERE ((feed_polls.feed_id = feeds.id) AND (feed_polls.outcome = 'failed'::text) AND ((( SELECT max(feed_polls_1.polled_at) AS max_1\n                   FROM feed_polls feed_polls_1\n                  WHERE ((feed_polls_1.feed_id = feeds.id) AND (feed_polls_1.outcome <> 'failed'::text))) IS NULL) OR (feed_polls.polled_at > ( SELECT max(feed_polls_1.polled_at) AS max_1\n                   FROM feed_polls feed_polls_1\n                  WHERE ((feed_polls_1.feed_id = feeds.id) AND (feed_polls_1.outcome <> 'failed'::text))))))) AS consecutive_failures,\n    (EXISTS ( SELECT feed_polls.id\n           FROM feed_polls\n          WHERE ((feed_polls.feed_id = feeds.id) AND (feed_polls.status = 410)))) AS gone,\n    ( SELECT feed_polls.outcome\n           FROM feed_polls\n          WHERE (feed_polls.feed_id = feeds.id)\n          ORDER BY feed_polls.polled_at DESC\n         LIMIT 1) AS last_outcome,\n    last_success_at,\n    next_poll_at\n   FROM feeds",
    )
    op.create_entity(public_feed_health)

    # ### end Alembic commands ###
