"""derived facts as views

Failure state has no column: it is counted off `feed_polls` and `page_captures` on demand,
so until now the only way to look at it was to write the subquery again by hand. These four
are that subquery, named — compiled in `db/views.py` from the same expression the ORM uses,
so a view and a hybrid cannot disagree.

Facts only. A threshold or a window is policy and stays in `config/`, which is why none of
these decides whether a host is refusing — only how many times it has failed.

`host_health` bakes the current capture policy into its definition, so bumping that wants a
revision too. Autogenerate notices; a stale view misleads a reader without misleading the
app, which reads the constant.

Revision ID: 7585999bead4
Revises: b0acf7d96d8b
Create Date: 2026-08-20 10:20:17.726485+00:00

"""

from collections.abc import Sequence

from alembic import op
from alembic_utils.pg_view import PGView

# revision identifiers, used by Alembic.
revision: str = "7585999bead4"
down_revision: str | Sequence[str] | None = "b0acf7d96d8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_feed_health = PGView(
        schema="public",
        signature="feed_health",
        definition="SELECT feeds.id AS feed_id, feeds.url AS url, (SELECT count(*) AS count_1 \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id AND feed_polls.outcome = 'failed' AND ((SELECT max(feed_polls_1.polled_at) AS max_1 \nFROM feed_polls AS feed_polls_1 \nWHERE feed_polls_1.feed_id = feeds.id AND feed_polls_1.outcome != 'failed') IS NULL OR feed_polls.polled_at > (SELECT max(feed_polls_1.polled_at) AS max_1 \nFROM feed_polls AS feed_polls_1 \nWHERE feed_polls_1.feed_id = feeds.id AND feed_polls_1.outcome != 'failed'))) AS consecutive_failures, EXISTS (SELECT feed_polls.id \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id AND feed_polls.status = 410) AS gone, (SELECT feed_polls.outcome \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id ORDER BY feed_polls.polled_at DESC \n LIMIT 1) AS last_outcome, feeds.last_success_at AS last_success_at, feeds.next_poll_at AS next_poll_at \nFROM feeds",
    )
    op.create_entity(public_feed_health)

    public_host_health = PGView(
        schema="public",
        signature="host_health",
        definition="SELECT hosts.id AS host_id, hosts.name AS name, (SELECT count(*) AS count_1 \nFROM page_captures \nWHERE page_captures.host_id = hosts.id AND page_captures.capture_policy = '2' AND page_captures.outcome = 'failed' AND ((SELECT max(page_captures_1.fetched_at) AS max_1 \nFROM page_captures AS page_captures_1 \nWHERE page_captures_1.host_id = hosts.id AND page_captures_1.capture_policy = '2' AND page_captures_1.outcome = 'ok') IS NULL OR page_captures.fetched_at > (SELECT max(page_captures_1.fetched_at) AS max_1 \nFROM page_captures AS page_captures_1 \nWHERE page_captures_1.host_id = hosts.id AND page_captures_1.capture_policy = '2' AND page_captures_1.outcome = 'ok'))) AS capture_failures, (SELECT max(page_captures.fetched_at) AS max_2 \nFROM page_captures \nWHERE page_captures.host_id = hosts.id AND page_captures.capture_policy = '2' AND page_captures.outcome = 'failed' AND ((SELECT max(page_captures_2.fetched_at) AS max_3 \nFROM page_captures AS page_captures_2 \nWHERE page_captures_2.host_id = hosts.id AND page_captures_2.capture_policy = '2' AND page_captures_2.outcome = 'ok') IS NULL OR page_captures.fetched_at > (SELECT max(page_captures_2.fetched_at) AS max_3 \nFROM page_captures AS page_captures_2 \nWHERE page_captures_2.host_id = hosts.id AND page_captures_2.capture_policy = '2' AND page_captures_2.outcome = 'ok'))) AS last_capture_failure, hosts.requires_www AS requires_www \nFROM hosts",
    )
    op.create_entity(public_host_health)

    public_item_reading = PGView(
        schema="public",
        signature="item_reading",
        definition="SELECT items.id AS item_id, CASE WHEN (length(coalesce((SELECT extractions.body \nFROM extractions JOIN item_versions ON item_versions.id = extractions.item_version_id \nWHERE item_versions.item_id = items.id ORDER BY extractions.created_at DESC, extractions.id DESC \n LIMIT 1), '')) > length((SELECT coalesce(nullif(item_versions.content, ''), item_versions.summary) AS coalesce_1 \nFROM item_versions \nWHERE items.id = item_versions.item_id AND NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id)) \n LIMIT 1))) THEN coalesce((SELECT extractions.body \nFROM extractions JOIN item_versions ON item_versions.id = extractions.item_version_id \nWHERE item_versions.item_id = items.id ORDER BY extractions.created_at DESC, extractions.id DESC \n LIMIT 1), '') ELSE (SELECT coalesce(nullif(item_versions.content, ''), item_versions.summary) AS coalesce_1 \nFROM item_versions \nWHERE items.id = item_versions.item_id AND NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id)) \n LIMIT 1) END AS reading_body \nFROM items",
    )
    op.create_entity(public_item_reading)

    public_reading_version = PGView(
        schema="public",
        signature="reading_version",
        definition="SELECT item_versions.id, item_versions.item_id, item_versions.document_id, item_versions.supersedes_id, item_versions.observed_at, item_versions.title, item_versions.author, item_versions.url, item_versions.canonical_url, item_versions.summary, item_versions.content, item_versions.tags, item_versions.enclosures, item_versions.comments_url, item_versions.published_at, item_versions.updated_at, item_versions.content_hash \nFROM item_versions \nWHERE NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id))",
    )
    op.create_entity(public_reading_version)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_reading_version = PGView(
        schema="public",
        signature="reading_version",
        definition="SELECT item_versions.id, item_versions.item_id, item_versions.document_id, item_versions.supersedes_id, item_versions.observed_at, item_versions.title, item_versions.author, item_versions.url, item_versions.canonical_url, item_versions.summary, item_versions.content, item_versions.tags, item_versions.enclosures, item_versions.comments_url, item_versions.published_at, item_versions.updated_at, item_versions.content_hash \nFROM item_versions \nWHERE NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id))",
    )
    op.drop_entity(public_reading_version)

    public_item_reading = PGView(
        schema="public",
        signature="item_reading",
        definition="SELECT items.id AS item_id, CASE WHEN (length(coalesce((SELECT extractions.body \nFROM extractions JOIN item_versions ON item_versions.id = extractions.item_version_id \nWHERE item_versions.item_id = items.id ORDER BY extractions.created_at DESC, extractions.id DESC \n LIMIT 1), '')) > length((SELECT coalesce(nullif(item_versions.content, ''), item_versions.summary) AS coalesce_1 \nFROM item_versions \nWHERE items.id = item_versions.item_id AND NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id)) \n LIMIT 1))) THEN coalesce((SELECT extractions.body \nFROM extractions JOIN item_versions ON item_versions.id = extractions.item_version_id \nWHERE item_versions.item_id = items.id ORDER BY extractions.created_at DESC, extractions.id DESC \n LIMIT 1), '') ELSE (SELECT coalesce(nullif(item_versions.content, ''), item_versions.summary) AS coalesce_1 \nFROM item_versions \nWHERE items.id = item_versions.item_id AND NOT (EXISTS (SELECT successor.id \nFROM item_versions AS successor \nWHERE successor.supersedes_id = item_versions.id)) \n LIMIT 1) END AS reading_body \nFROM items",
    )
    op.drop_entity(public_item_reading)

    public_host_health = PGView(
        schema="public",
        signature="host_health",
        definition="SELECT hosts.id AS host_id, hosts.name AS name, (SELECT count(*) AS count_1 \nFROM page_captures \nWHERE page_captures.host_id = hosts.id AND page_captures.capture_policy = '2' AND page_captures.outcome = 'failed' AND ((SELECT max(page_captures_1.fetched_at) AS max_1 \nFROM page_captures AS page_captures_1 \nWHERE page_captures_1.host_id = hosts.id AND page_captures_1.capture_policy = '2' AND page_captures_1.outcome = 'ok') IS NULL OR page_captures.fetched_at > (SELECT max(page_captures_1.fetched_at) AS max_1 \nFROM page_captures AS page_captures_1 \nWHERE page_captures_1.host_id = hosts.id AND page_captures_1.capture_policy = '2' AND page_captures_1.outcome = 'ok'))) AS capture_failures, (SELECT max(page_captures.fetched_at) AS max_2 \nFROM page_captures \nWHERE page_captures.host_id = hosts.id AND page_captures.capture_policy = '2' AND page_captures.outcome = 'failed' AND ((SELECT max(page_captures_2.fetched_at) AS max_3 \nFROM page_captures AS page_captures_2 \nWHERE page_captures_2.host_id = hosts.id AND page_captures_2.capture_policy = '2' AND page_captures_2.outcome = 'ok') IS NULL OR page_captures.fetched_at > (SELECT max(page_captures_2.fetched_at) AS max_3 \nFROM page_captures AS page_captures_2 \nWHERE page_captures_2.host_id = hosts.id AND page_captures_2.capture_policy = '2' AND page_captures_2.outcome = 'ok'))) AS last_capture_failure, hosts.requires_www AS requires_www \nFROM hosts",
    )
    op.drop_entity(public_host_health)

    public_feed_health = PGView(
        schema="public",
        signature="feed_health",
        definition="SELECT feeds.id AS feed_id, feeds.url AS url, (SELECT count(*) AS count_1 \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id AND feed_polls.outcome = 'failed' AND ((SELECT max(feed_polls_1.polled_at) AS max_1 \nFROM feed_polls AS feed_polls_1 \nWHERE feed_polls_1.feed_id = feeds.id AND feed_polls_1.outcome != 'failed') IS NULL OR feed_polls.polled_at > (SELECT max(feed_polls_1.polled_at) AS max_1 \nFROM feed_polls AS feed_polls_1 \nWHERE feed_polls_1.feed_id = feeds.id AND feed_polls_1.outcome != 'failed'))) AS consecutive_failures, EXISTS (SELECT feed_polls.id \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id AND feed_polls.status = 410) AS gone, (SELECT feed_polls.outcome \nFROM feed_polls \nWHERE feed_polls.feed_id = feeds.id ORDER BY feed_polls.polled_at DESC \n LIMIT 1) AS last_outcome, feeds.last_success_at AS last_success_at, feeds.next_poll_at AS next_poll_at \nFROM feeds",
    )
    op.drop_entity(public_feed_health)

    # ### end Alembic commands ###
