"""add robots policies

One row per host, overwritten by the refresh task. Keyed by host rather than by feed
because many feeds share one, and no foreign key because the row is a rebuildable
cache whose life is not tied to a subscription.

Revision ID: fbddd5978dfe
Revises: fd3da7760685
Create Date: 2026-08-18 01:07:35.494290+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbddd5978dfe"
down_revision: str | Sequence[str] | None = "fd3da7760685"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "robots_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("host", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), server_default="", nullable=False),
        sa.Column("crawl_delay_seconds", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robots_policies")),
    )
    op.create_index(op.f("ix_robots_policies_host"), "robots_policies", ["host"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_robots_policies_host"), table_name="robots_policies")
    op.drop_table("robots_policies")
    # ### end Alembic commands ###
