"""initial schema

Revision ID: 79a05d3214fd
Revises:
Create Date: 2026-08-14 04:46:41.981052+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79a05d3214fd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeds",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("site_url", sa.Text(), server_default="", nullable=False),
        sa.Column("title", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("language", sa.String(length=32), server_default="", nullable=False),
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("icon_url", sa.Text(), server_default="", nullable=False),
        sa.Column("platform", sa.Text(), server_default="", nullable=False),
        sa.Column("ttl_seconds", sa.Integer(), nullable=True),
        sa.Column("hub_url", sa.Text(), server_default="", nullable=False),
        sa.Column("etag", sa.Text(), server_default="", nullable=False),
        sa.Column("last_modified", sa.Text(), server_default="", nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_poll_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), server_default="", nullable=False),
        sa.Column("suspended", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("suspended_reason", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeds")),
    )
    op.create_index(op.f("ix_feeds_next_poll_at"), "feeds", ["next_poll_at"], unique=False)
    op.create_index(op.f("ix_feeds_suspended"), "feeds", ["suspended"], unique=False)
    op.create_index(op.f("ix_feeds_url"), "feeds", ["url"], unique=True)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("body_hash", sa.LargeBinary(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column(
            "headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("parse_ok", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("parse_note", sa.Text(), server_default="", nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_documents_feed_id_feeds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        "ix_documents_feed_fetched",
        "documents",
        ["feed_id", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("guid", sa.Text(), server_default="", nullable=False),
        sa.Column("identity_key", sa.Text(), nullable=False),
        sa.Column("identity_source", sa.String(length=8), server_default="guid", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"], ["feeds.id"], name=op.f("fk_items_feed_id_feeds"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("feed_id", "identity_key", name="uq_items_feed_identity"),
    )
    op.create_index(
        "ix_items_feed_first_seen",
        "items",
        ["feed_id", sa.literal_column("first_seen_at DESC"), "id"],
        unique=False,
    )
    op.create_index(op.f("ix_items_first_seen_at"), "items", ["first_seen_at"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), server_default="", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            name=op.f("fk_subscriptions_feed_id_feeds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("feed_id", name=op.f("uq_subscriptions_feed_id")),
    )
    op.create_index(op.f("ix_subscriptions_active"), "subscriptions", ["active"], unique=False)
    op.create_index(op.f("ix_subscriptions_category"), "subscriptions", ["category"], unique=False)
    op.create_table(
        "item_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), server_default="", nullable=False),
        sa.Column("author", sa.Text(), server_default="", nullable=False),
        sa.Column("url", sa.Text(), server_default="", nullable=False),
        sa.Column("canonical_url", sa.Text(), server_default="", nullable=False),
        sa.Column("summary", sa.Text(), server_default="", nullable=False),
        sa.Column("content", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "enclosures",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("comments_url", sa.Text(), server_default="", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR id > supersedes_id", name=op.f("ck_item_versions_key_order")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_item_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_item_versions_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["item_versions.id"],
            name=op.f("fk_item_versions_supersedes_id_item_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_versions")),
        sa.UniqueConstraint("supersedes_id", name="uq_item_versions_supersedes"),
    )
    op.create_index(
        op.f("ix_item_versions_canonical_url"), "item_versions", ["canonical_url"], unique=False
    )
    op.create_index("ix_item_versions_item_id", "item_versions", ["item_id", "id"], unique=False)
    op.create_index(
        op.f("ix_item_versions_observed_at"), "item_versions", ["observed_at"], unique=False
    )
    op.create_index(
        "uq_item_versions_head",
        "item_versions",
        ["item_id"],
        unique=True,
        postgresql_where=sa.text("supersedes_id IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_item_versions_head",
        table_name="item_versions",
        postgresql_where=sa.text("supersedes_id IS NULL"),
    )
    op.drop_index(op.f("ix_item_versions_observed_at"), table_name="item_versions")
    op.drop_index("ix_item_versions_item_id", table_name="item_versions")
    op.drop_index(op.f("ix_item_versions_canonical_url"), table_name="item_versions")
    op.drop_table("item_versions")
    op.drop_index(op.f("ix_subscriptions_category"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_active"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_items_first_seen_at"), table_name="items")
    op.drop_index("ix_items_feed_first_seen", table_name="items")
    op.drop_table("items")
    op.drop_index("ix_documents_feed_fetched", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_feeds_url"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_suspended"), table_name="feeds")
    op.drop_index(op.f("ix_feeds_next_poll_at"), table_name="feeds")
    op.drop_table("feeds")
    # ### end Alembic commands ###
