"""save an item

Saving is a collection in the archive and nothing else: it does not hold an item in the
river. A timestamp rather than a flag, beside `read_at` and `finished_at`, because it is
the same kind of hand-made per-item state. A saved wire item also gets its body images,
which is the one place saving changes what is captured. Unsaving clears the column and
leaves whatever was captured alone.

No index. The archive filters a few thousand rows and the image sweep already joins on
the item, so a partial index on saved items would be paid for on every write for nothing
yet.

Revision ID: 653d469e05f8
Revises: 8cd702379b3d
Create Date: 2026-10-01 05:57:37.268492+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "653d469e05f8"
down_revision: str | Sequence[str] | None = "8cd702379b3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "saved_at")
    # ### end Alembic commands ###
