# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .check import *
from .get_channel import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_healthchecksio.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_healthchecksio.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "healthchecksio",
  "mod": "index/check",
  "fqn": "pulumi_healthchecksio",
  "classes": {
   "healthchecksio:index/check:Check": "Check"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "healthchecksio",
  "token": "pulumi:providers:healthchecksio",
  "fqn": "pulumi_healthchecksio",
  "class": "Provider"
 }
]
"""
)
