# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CheckArgs', 'Check']

@pulumi.input_type
class CheckArgs:
    def __init__(__self__, *,
                 channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 check_id: pulumi.Input[Optional[_builtins.str]] = None,
                 desc: pulumi.Input[Optional[_builtins.str]] = None,
                 grace: pulumi.Input[Optional[_builtins.float]] = None,
                 methods: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout: pulumi.Input[Optional[_builtins.float]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Check resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channels: Channels integrated with the check
        :param pulumi.Input[_builtins.str] desc: Description of the check
        :param pulumi.Input[_builtins.float] grace: Grace period for the check
        :param pulumi.Input[_builtins.str] methods: Allowed HTTP methods for making ping requests
        :param pulumi.Input[_builtins.str] name: Name of the check
        :param pulumi.Input[_builtins.str] schedule: A cron expression defining the check's schedule
        :param pulumi.Input[_builtins.str] slug: Slug of the check
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the check
        :param pulumi.Input[_builtins.float] timeout: Timeout period of the check
        :param pulumi.Input[_builtins.str] timezone: Timezone used for the schedule
        """
        if channels is not None:
            pulumi.set(__self__, "channels", channels)
        if check_id is not None:
            pulumi.set(__self__, "check_id", check_id)
        if desc is not None:
            pulumi.set(__self__, "desc", desc)
        if grace is not None:
            pulumi.set(__self__, "grace", grace)
        if methods is not None:
            pulumi.set(__self__, "methods", methods)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if schedule is not None:
            pulumi.set(__self__, "schedule", schedule)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter
    def channels(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Channels integrated with the check
        """
        return pulumi.get(self, "channels")

    @channels.setter
    def channels(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "channels", value)

    @_builtins.property
    @pulumi.getter(name="checkId")
    def check_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "check_id")

    @check_id.setter
    def check_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "check_id", value)

    @_builtins.property
    @pulumi.getter
    def desc(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the check
        """
        return pulumi.get(self, "desc")

    @desc.setter
    def desc(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "desc", value)

    @_builtins.property
    @pulumi.getter
    def grace(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Grace period for the check
        """
        return pulumi.get(self, "grace")

    @grace.setter
    def grace(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "grace", value)

    @_builtins.property
    @pulumi.getter
    def methods(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Allowed HTTP methods for making ping requests
        """
        return pulumi.get(self, "methods")

    @methods.setter
    def methods(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "methods", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the check
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A cron expression defining the check's schedule
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Slug of the check
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Tags associated with the check
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Timeout period of the check
        """
        return pulumi.get(self, "timeout")

    @timeout.setter
    def timeout(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "timeout", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timezone used for the schedule
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.input_type
class _CheckState:
    def __init__(__self__, *,
                 channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 check_id: pulumi.Input[Optional[_builtins.str]] = None,
                 desc: pulumi.Input[Optional[_builtins.str]] = None,
                 grace: pulumi.Input[Optional[_builtins.float]] = None,
                 methods: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 pause_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ping_url: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout: pulumi.Input[Optional[_builtins.float]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Check resources.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channels: Channels integrated with the check
        :param pulumi.Input[_builtins.str] desc: Description of the check
        :param pulumi.Input[_builtins.float] grace: Grace period for the check
        :param pulumi.Input[_builtins.str] methods: Allowed HTTP methods for making ping requests
        :param pulumi.Input[_builtins.str] name: Name of the check
        :param pulumi.Input[_builtins.str] pause_url: Pause URL associated with this check
        :param pulumi.Input[_builtins.str] ping_url: Ping URL associated with this check
        :param pulumi.Input[_builtins.str] schedule: A cron expression defining the check's schedule
        :param pulumi.Input[_builtins.str] slug: Slug of the check
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the check
        :param pulumi.Input[_builtins.float] timeout: Timeout period of the check
        :param pulumi.Input[_builtins.str] timezone: Timezone used for the schedule
        """
        if channels is not None:
            pulumi.set(__self__, "channels", channels)
        if check_id is not None:
            pulumi.set(__self__, "check_id", check_id)
        if desc is not None:
            pulumi.set(__self__, "desc", desc)
        if grace is not None:
            pulumi.set(__self__, "grace", grace)
        if methods is not None:
            pulumi.set(__self__, "methods", methods)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if pause_url is not None:
            pulumi.set(__self__, "pause_url", pause_url)
        if ping_url is not None:
            pulumi.set(__self__, "ping_url", ping_url)
        if schedule is not None:
            pulumi.set(__self__, "schedule", schedule)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)
        if timezone is not None:
            pulumi.set(__self__, "timezone", timezone)

    @_builtins.property
    @pulumi.getter
    def channels(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Channels integrated with the check
        """
        return pulumi.get(self, "channels")

    @channels.setter
    def channels(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "channels", value)

    @_builtins.property
    @pulumi.getter(name="checkId")
    def check_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "check_id")

    @check_id.setter
    def check_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "check_id", value)

    @_builtins.property
    @pulumi.getter
    def desc(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the check
        """
        return pulumi.get(self, "desc")

    @desc.setter
    def desc(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "desc", value)

    @_builtins.property
    @pulumi.getter
    def grace(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Grace period for the check
        """
        return pulumi.get(self, "grace")

    @grace.setter
    def grace(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "grace", value)

    @_builtins.property
    @pulumi.getter
    def methods(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Allowed HTTP methods for making ping requests
        """
        return pulumi.get(self, "methods")

    @methods.setter
    def methods(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "methods", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the check
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="pauseUrl")
    def pause_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Pause URL associated with this check
        """
        return pulumi.get(self, "pause_url")

    @pause_url.setter
    def pause_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "pause_url", value)

    @_builtins.property
    @pulumi.getter(name="pingUrl")
    def ping_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Ping URL associated with this check
        """
        return pulumi.get(self, "ping_url")

    @ping_url.setter
    def ping_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ping_url", value)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A cron expression defining the check's schedule
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Slug of the check
        """
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Tags associated with the check
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Timeout period of the check
        """
        return pulumi.get(self, "timeout")

    @timeout.setter
    def timeout(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "timeout", value)

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Timezone used for the schedule
        """
        return pulumi.get(self, "timezone")

    @timezone.setter
    def timezone(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "timezone", value)


@pulumi.type_token("healthchecksio:index/check:Check")
class Check(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 check_id: pulumi.Input[Optional[_builtins.str]] = None,
                 desc: pulumi.Input[Optional[_builtins.str]] = None,
                 grace: pulumi.Input[Optional[_builtins.float]] = None,
                 methods: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout: pulumi.Input[Optional[_builtins.float]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Check resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channels: Channels integrated with the check
        :param pulumi.Input[_builtins.str] desc: Description of the check
        :param pulumi.Input[_builtins.float] grace: Grace period for the check
        :param pulumi.Input[_builtins.str] methods: Allowed HTTP methods for making ping requests
        :param pulumi.Input[_builtins.str] name: Name of the check
        :param pulumi.Input[_builtins.str] schedule: A cron expression defining the check's schedule
        :param pulumi.Input[_builtins.str] slug: Slug of the check
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the check
        :param pulumi.Input[_builtins.float] timeout: Timeout period of the check
        :param pulumi.Input[_builtins.str] timezone: Timezone used for the schedule
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[CheckArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Check resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param CheckArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CheckArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 check_id: pulumi.Input[Optional[_builtins.str]] = None,
                 desc: pulumi.Input[Optional[_builtins.str]] = None,
                 grace: pulumi.Input[Optional[_builtins.float]] = None,
                 methods: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 schedule: pulumi.Input[Optional[_builtins.str]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout: pulumi.Input[Optional[_builtins.float]] = None,
                 timezone: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CheckArgs.__new__(CheckArgs)

            __props__.__dict__["channels"] = channels
            __props__.__dict__["check_id"] = check_id
            __props__.__dict__["desc"] = desc
            __props__.__dict__["grace"] = grace
            __props__.__dict__["methods"] = methods
            __props__.__dict__["name"] = name
            __props__.__dict__["schedule"] = schedule
            __props__.__dict__["slug"] = slug
            __props__.__dict__["tags"] = tags
            __props__.__dict__["timeout"] = timeout
            __props__.__dict__["timezone"] = timezone
            __props__.__dict__["pause_url"] = None
            __props__.__dict__["ping_url"] = None
        super(Check, __self__).__init__(
            'healthchecksio:index/check:Check',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            channels: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            check_id: pulumi.Input[Optional[_builtins.str]] = None,
            desc: pulumi.Input[Optional[_builtins.str]] = None,
            grace: pulumi.Input[Optional[_builtins.float]] = None,
            methods: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            pause_url: pulumi.Input[Optional[_builtins.str]] = None,
            ping_url: pulumi.Input[Optional[_builtins.str]] = None,
            schedule: pulumi.Input[Optional[_builtins.str]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None,
            tags: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            timeout: pulumi.Input[Optional[_builtins.float]] = None,
            timezone: pulumi.Input[Optional[_builtins.str]] = None) -> 'Check':
        """
        Get an existing Check resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] channels: Channels integrated with the check
        :param pulumi.Input[_builtins.str] desc: Description of the check
        :param pulumi.Input[_builtins.float] grace: Grace period for the check
        :param pulumi.Input[_builtins.str] methods: Allowed HTTP methods for making ping requests
        :param pulumi.Input[_builtins.str] name: Name of the check
        :param pulumi.Input[_builtins.str] pause_url: Pause URL associated with this check
        :param pulumi.Input[_builtins.str] ping_url: Ping URL associated with this check
        :param pulumi.Input[_builtins.str] schedule: A cron expression defining the check's schedule
        :param pulumi.Input[_builtins.str] slug: Slug of the check
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: Tags associated with the check
        :param pulumi.Input[_builtins.float] timeout: Timeout period of the check
        :param pulumi.Input[_builtins.str] timezone: Timezone used for the schedule
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CheckState.__new__(_CheckState)

        __props__.__dict__["channels"] = channels
        __props__.__dict__["check_id"] = check_id
        __props__.__dict__["desc"] = desc
        __props__.__dict__["grace"] = grace
        __props__.__dict__["methods"] = methods
        __props__.__dict__["name"] = name
        __props__.__dict__["pause_url"] = pause_url
        __props__.__dict__["ping_url"] = ping_url
        __props__.__dict__["schedule"] = schedule
        __props__.__dict__["slug"] = slug
        __props__.__dict__["tags"] = tags
        __props__.__dict__["timeout"] = timeout
        __props__.__dict__["timezone"] = timezone
        return Check(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def channels(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Channels integrated with the check
        """
        return pulumi.get(self, "channels")

    @_builtins.property
    @pulumi.getter(name="checkId")
    def check_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "check_id")

    @_builtins.property
    @pulumi.getter
    def desc(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the check
        """
        return pulumi.get(self, "desc")

    @_builtins.property
    @pulumi.getter
    def grace(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Grace period for the check
        """
        return pulumi.get(self, "grace")

    @_builtins.property
    @pulumi.getter
    def methods(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Allowed HTTP methods for making ping requests
        """
        return pulumi.get(self, "methods")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the check
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="pauseUrl")
    def pause_url(self) -> pulumi.Output[_builtins.str]:
        """
        Pause URL associated with this check
        """
        return pulumi.get(self, "pause_url")

    @_builtins.property
    @pulumi.getter(name="pingUrl")
    def ping_url(self) -> pulumi.Output[_builtins.str]:
        """
        Ping URL associated with this check
        """
        return pulumi.get(self, "ping_url")

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A cron expression defining the check's schedule
        """
        return pulumi.get(self, "schedule")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        """
        Slug of the check
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Tags associated with the check
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Timeout period of the check
        """
        return pulumi.get(self, "timeout")

    @_builtins.property
    @pulumi.getter
    def timezone(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Timezone used for the schedule
        """
        return pulumi.get(self, "timezone")

