import enum
import uuid

from sqlalchemy import DateTime, MetaData, text
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Alembic names constraints after whatever Postgres invented unless it is told
# otherwise, which makes autogenerated migrations churn. This pins them.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

Timestamptz = DateTime(timezone=True)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKey:
    """uuidv7 primary keys, generated by Postgres."""

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuidv7()"),
        # Mixin columns are appended by default, which puts the primary key last
        # in every table.
        sort_order=-1,
    )


NOW = text("CURRENT_TIMESTAMP")


def one_of(column: str, allowed: type[enum.StrEnum]) -> str:
    """A check constraint spelled from an enum's members.

    Enums in Python, strings in Postgres. `sa.Enum` does neither half well: a native type
    cannot gain a value in the same transaction as the migration needing it, and with
    `native_enum=False` alembic renders the member *names* into the constraint where the
    application writes the *values*, so every insert fails.
    """
    values = ", ".join(f"'{member.value}'" for member in allowed)
    return f"{column} IN ({values})"
