# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import sys

if sys.version_info >= (3, 11):
    pass
else:
    pass

applicationKey: str | None
"""
B2 Application Key (B2_APPLICATION_KEY env).
"""

applicationKeyId: str | None
"""
B2 Application Key ID (B2_APPLICATION_KEY_ID env).
"""

endpoint: str | None
"""
B2 endpoint - the string 'production' or a custom B2 API URL (B2_ENDPOINT env). You should not need to set this unless you work at Backblaze. Defaults to <span pulumi-lang-nodejs="`production`" pulumi-lang-dotnet="`Production`" pulumi-lang-go="`production`" pulumi-lang-python="`production`" pulumi-lang-yaml="`production`" pulumi-lang-java="`production`" pulumi-lang-hcl="`production`">`production`</span>.
"""
