# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict
else:
    from typing import NotRequired

    from typing_extensions import TypedDict

__all__ = [
    "ChannelConfigArgs",
    "ChannelConfigArgsDict",
]


class ChannelConfigArgsDict(TypedDict):
    type: pulumi.Input[_builtins.str]
    """
    Channel type (<span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span>, <span pulumi-lang-nodejs="`opsgenie`" pulumi-lang-dotnet="`Opsgenie`" pulumi-lang-go="`opsgenie`" pulumi-lang-python="`opsgenie`" pulumi-lang-yaml="`opsgenie`" pulumi-lang-java="`opsgenie`" pulumi-lang-hcl="`opsgenie`">`opsgenie`</span>, <span pulumi-lang-nodejs="`pagerduty`" pulumi-lang-dotnet="`Pagerduty`" pulumi-lang-go="`pagerduty`" pulumi-lang-python="`pagerduty`" pulumi-lang-yaml="`pagerduty`" pulumi-lang-java="`pagerduty`" pulumi-lang-hcl="`pagerduty`">`pagerduty`</span>, or `slack-integration`).
    """
    auth_key: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    Opsgenie API key.
    """
    channel_id: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
    """
    format: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    Webhook payload format.
    """
    include_agent_prompt: NotRequired[pulumi.Input[_builtins.bool | None]]
    """
    Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when omitted.
    """
    install_id: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
    """
    region: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    PagerDuty account region (<span pulumi-lang-nodejs="`us`" pulumi-lang-dotnet="`Us`" pulumi-lang-go="`us`" pulumi-lang-python="`us`" pulumi-lang-yaml="`us`" pulumi-lang-java="`us`" pulumi-lang-hcl="`us`">`us`</span> or <span pulumi-lang-nodejs="`eu`" pulumi-lang-dotnet="`Eu`" pulumi-lang-go="`eu`" pulumi-lang-python="`eu`" pulumi-lang-yaml="`eu`" pulumi-lang-java="`eu`" pulumi-lang-hcl="`eu`">`eu`</span>). When omitted, Logfire uses the US Events API endpoint.
    """
    routing_key: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    PagerDuty Events API v2 integration routing key.
    """
    url: NotRequired[pulumi.Input[_builtins.str | None]]
    """
    Webhook URL endpoint.
    """


@pulumi.input_type
class ChannelConfigArgs:
    def __init__(
        __self__,
        *,
        type: pulumi.Input[_builtins.str],
        auth_key: pulumi.Input[_builtins.str | None] = None,
        channel_id: pulumi.Input[_builtins.str | None] = None,
        format: pulumi.Input[_builtins.str | None] = None,
        include_agent_prompt: pulumi.Input[_builtins.bool | None] = None,
        install_id: pulumi.Input[_builtins.str | None] = None,
        region: pulumi.Input[_builtins.str | None] = None,
        routing_key: pulumi.Input[_builtins.str | None] = None,
        url: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        :param pulumi.Input[_builtins.str] type: Channel type (<span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span>, <span pulumi-lang-nodejs="`opsgenie`" pulumi-lang-dotnet="`Opsgenie`" pulumi-lang-go="`opsgenie`" pulumi-lang-python="`opsgenie`" pulumi-lang-yaml="`opsgenie`" pulumi-lang-java="`opsgenie`" pulumi-lang-hcl="`opsgenie`">`opsgenie`</span>, <span pulumi-lang-nodejs="`pagerduty`" pulumi-lang-dotnet="`Pagerduty`" pulumi-lang-go="`pagerduty`" pulumi-lang-python="`pagerduty`" pulumi-lang-yaml="`pagerduty`" pulumi-lang-java="`pagerduty`" pulumi-lang-hcl="`pagerduty`">`pagerduty`</span>, or `slack-integration`).
        :param pulumi.Input[_builtins.str] auth_key: Opsgenie API key.
        :param pulumi.Input[_builtins.str] channel_id: Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        :param pulumi.Input[_builtins.str] format: Webhook payload format.
        :param pulumi.Input[_builtins.bool] include_agent_prompt: Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when omitted.
        :param pulumi.Input[_builtins.str] install_id: ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
        :param pulumi.Input[_builtins.str] region: PagerDuty account region (<span pulumi-lang-nodejs="`us`" pulumi-lang-dotnet="`Us`" pulumi-lang-go="`us`" pulumi-lang-python="`us`" pulumi-lang-yaml="`us`" pulumi-lang-java="`us`" pulumi-lang-hcl="`us`">`us`</span> or <span pulumi-lang-nodejs="`eu`" pulumi-lang-dotnet="`Eu`" pulumi-lang-go="`eu`" pulumi-lang-python="`eu`" pulumi-lang-yaml="`eu`" pulumi-lang-java="`eu`" pulumi-lang-hcl="`eu`">`eu`</span>). When omitted, Logfire uses the US Events API endpoint.
        :param pulumi.Input[_builtins.str] routing_key: PagerDuty Events API v2 integration routing key.
        :param pulumi.Input[_builtins.str] url: Webhook URL endpoint.
        """
        pulumi.set(__self__, "type", type)
        if auth_key is not None:
            pulumi.set(__self__, "auth_key", auth_key)
        if channel_id is not None:
            pulumi.set(__self__, "channel_id", channel_id)
        if format is not None:
            pulumi.set(__self__, "format", format)
        if include_agent_prompt is not None:
            pulumi.set(__self__, "include_agent_prompt", include_agent_prompt)
        if install_id is not None:
            pulumi.set(__self__, "install_id", install_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if routing_key is not None:
            pulumi.set(__self__, "routing_key", routing_key)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Channel type (<span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span>, <span pulumi-lang-nodejs="`opsgenie`" pulumi-lang-dotnet="`Opsgenie`" pulumi-lang-go="`opsgenie`" pulumi-lang-python="`opsgenie`" pulumi-lang-yaml="`opsgenie`" pulumi-lang-java="`opsgenie`" pulumi-lang-hcl="`opsgenie`">`opsgenie`</span>, <span pulumi-lang-nodejs="`pagerduty`" pulumi-lang-dotnet="`Pagerduty`" pulumi-lang-go="`pagerduty`" pulumi-lang-python="`pagerduty`" pulumi-lang-yaml="`pagerduty`" pulumi-lang-java="`pagerduty`" pulumi-lang-hcl="`pagerduty`">`pagerduty`</span>, or `slack-integration`).
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="authKey")
    def auth_key(self) -> pulumi.Input[_builtins.str | None]:
        """
        Opsgenie API key.
        """
        return pulumi.get(self, "auth_key")

    @auth_key.setter
    def auth_key(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "auth_key", value)

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        """
        return pulumi.get(self, "channel_id")

    @channel_id.setter
    def channel_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "channel_id", value)

    @_builtins.property
    @pulumi.getter
    def format(self) -> pulumi.Input[_builtins.str | None]:
        """
        Webhook payload format.
        """
        return pulumi.get(self, "format")

    @format.setter
    def format(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "format", value)

    @_builtins.property
    @pulumi.getter(name="includeAgentPrompt")
    def include_agent_prompt(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when omitted.
        """
        return pulumi.get(self, "include_agent_prompt")

    @include_agent_prompt.setter
    def include_agent_prompt(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "include_agent_prompt", value)

    @_builtins.property
    @pulumi.getter(name="installId")
    def install_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
        """
        return pulumi.get(self, "install_id")

    @install_id.setter
    def install_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "install_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str | None]:
        """
        PagerDuty account region (<span pulumi-lang-nodejs="`us`" pulumi-lang-dotnet="`Us`" pulumi-lang-go="`us`" pulumi-lang-python="`us`" pulumi-lang-yaml="`us`" pulumi-lang-java="`us`" pulumi-lang-hcl="`us`">`us`</span> or <span pulumi-lang-nodejs="`eu`" pulumi-lang-dotnet="`Eu`" pulumi-lang-go="`eu`" pulumi-lang-python="`eu`" pulumi-lang-yaml="`eu`" pulumi-lang-java="`eu`" pulumi-lang-hcl="`eu`">`eu`</span>). When omitted, Logfire uses the US Events API endpoint.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="routingKey")
    def routing_key(self) -> pulumi.Input[_builtins.str | None]:
        """
        PagerDuty Events API v2 integration routing key.
        """
        return pulumi.get(self, "routing_key")

    @routing_key.setter
    def routing_key(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "routing_key", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[_builtins.str | None]:
        """
        Webhook URL endpoint.
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "url", value)
