# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities, outputs
from ._inputs import *

__all__ = ["Channel", "ChannelArgs"]


@pulumi.input_type
class ChannelArgs:
    def __init__(
        __self__,
        *,
        active: pulumi.Input[_builtins.bool | None] = None,
        config: pulumi.Input[ChannelConfigArgs | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        The set of arguments for constructing a Channel resource.

        :param pulumi.Input[_builtins.bool] active: Whether the channel is active.
        :param pulumi.Input['ChannelConfigArgs'] config: Required channel configuration.
        :param pulumi.Input[_builtins.str] name: Channel name.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether the channel is active.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[ChannelConfigArgs | None]:
        """
        Required channel configuration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[ChannelConfigArgs | None]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Channel name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _ChannelState:
    def __init__(
        __self__,
        *,
        active: pulumi.Input[_builtins.bool | None] = None,
        config: pulumi.Input[ChannelConfigArgs | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        Input properties used for looking up and filtering Channel resources.

        :param pulumi.Input[_builtins.bool] active: Whether the channel is active.
        :param pulumi.Input['ChannelConfigArgs'] config: Required channel configuration.
        :param pulumi.Input[_builtins.str] name: Channel name.
        """
        if active is not None:
            pulumi.set(__self__, "active", active)
        if config is not None:
            pulumi.set(__self__, "config", config)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether the channel is active.
        """
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Input[ChannelConfigArgs | None]:
        """
        Required channel configuration.
        """
        return pulumi.get(self, "config")

    @config.setter
    def config(self, value: pulumi.Input[ChannelConfigArgs | None]):
        pulumi.set(self, "config", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Channel name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)


@pulumi.type_token("logfire:index/channel:Channel")
class Channel(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        active: pulumi.Input[_builtins.bool | None] = None,
        config: pulumi.Input[ChannelConfigArgs | ChannelConfigArgsDict | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        """
        Create a Channel resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Whether the channel is active.
        :param pulumi.Input[Union['ChannelConfigArgs', 'ChannelConfigArgsDict']] config: Required channel configuration.
        :param pulumi.Input[_builtins.str] name: Channel name.
        """
        ...

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: ChannelArgs | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Create a Channel resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ChannelArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            ChannelArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        active: pulumi.Input[_builtins.bool | None] = None,
        config: pulumi.Input[ChannelConfigArgs | ChannelConfigArgsDict | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError("Expected resource options to be a ResourceOptions instance")
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = ChannelArgs.__new__(ChannelArgs)

            __props__.__dict__["active"] = active
            __props__.__dict__["config"] = config
            __props__.__dict__["name"] = name
        super().__init__(
            "logfire:index/channel:Channel",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        active: pulumi.Input[_builtins.bool | None] = None,
        config: pulumi.Input[ChannelConfigArgs | ChannelConfigArgsDict | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
    ) -> Channel:
        """
        Get an existing Channel resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] active: Whether the channel is active.
        :param pulumi.Input[Union['ChannelConfigArgs', 'ChannelConfigArgsDict']] config: Required channel configuration.
        :param pulumi.Input[_builtins.str] name: Channel name.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ChannelState.__new__(_ChannelState)

        __props__.__dict__["active"] = active
        __props__.__dict__["config"] = config
        __props__.__dict__["name"] = name
        return Channel(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the channel is active.
        """
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def config(self) -> pulumi.Output[outputs.ChannelConfig | None]:
        """
        Required channel configuration.
        """
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Channel name.
        """
        return pulumi.get(self, "name")
