# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = ["Organization", "OrganizationArgs"]


@pulumi.input_type
class OrganizationArgs:
    def __init__(
        __self__,
        *,
        avatar: pulumi.Input[_builtins.str | None] = None,
        billing_email: pulumi.Input[_builtins.str | None] = None,
        deletion_protection: pulumi.Input[_builtins.bool | None] = None,
        description: pulumi.Input[_builtins.str | None] = None,
        display_name: pulumi.Input[_builtins.str | None] = None,
        github_handle: pulumi.Input[_builtins.str | None] = None,
        location: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        The set of arguments for constructing a Organization resource.

        :param pulumi.Input[_builtins.str] avatar: Avatar URL.
        :param pulumi.Input[_builtins.str] billing_email: Billing contact email.
        :param pulumi.Input[_builtins.bool] deletion_protection: Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        :param pulumi.Input[_builtins.str] description: Organization description.
        :param pulumi.Input[_builtins.str] display_name: Display name shown in the UI.
        :param pulumi.Input[_builtins.str] github_handle: Organization GitHub handle.
        :param pulumi.Input[_builtins.str] location: Organization location.
        :param pulumi.Input[_builtins.str] name: Organization name/slug.
        """
        if avatar is not None:
            pulumi.set(__self__, "avatar", avatar)
        if billing_email is not None:
            pulumi.set(__self__, "billing_email", billing_email)
        if deletion_protection is not None:
            pulumi.set(__self__, "deletion_protection", deletion_protection)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if github_handle is not None:
            pulumi.set(__self__, "github_handle", github_handle)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter
    def avatar(self) -> pulumi.Input[_builtins.str | None]:
        """
        Avatar URL.
        """
        return pulumi.get(self, "avatar")

    @avatar.setter
    def avatar(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "avatar", value)

    @_builtins.property
    @pulumi.getter(name="billingEmail")
    def billing_email(self) -> pulumi.Input[_builtins.str | None]:
        """
        Billing contact email.
        """
        return pulumi.get(self, "billing_email")

    @billing_email.setter
    def billing_email(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "billing_email", value)

    @_builtins.property
    @pulumi.getter(name="deletionProtection")
    def deletion_protection(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        """
        return pulumi.get(self, "deletion_protection")

    @deletion_protection.setter
    def deletion_protection(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "deletion_protection", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Display name shown in the UI.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="githubHandle")
    def github_handle(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization GitHub handle.
        """
        return pulumi.get(self, "github_handle")

    @github_handle.setter
    def github_handle(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "github_handle", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization location.
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization name/slug.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _OrganizationState:
    def __init__(
        __self__,
        *,
        ai_enabled: pulumi.Input[_builtins.bool | None] = None,
        avatar: pulumi.Input[_builtins.str | None] = None,
        billing_email: pulumi.Input[_builtins.str | None] = None,
        created_at: pulumi.Input[_builtins.str | None] = None,
        deletion_protection: pulumi.Input[_builtins.bool | None] = None,
        description: pulumi.Input[_builtins.str | None] = None,
        display_name: pulumi.Input[_builtins.str | None] = None,
        gateway_enabled: pulumi.Input[_builtins.bool | None] = None,
        github_handle: pulumi.Input[_builtins.str | None] = None,
        has_admin_panel: pulumi.Input[_builtins.bool | None] = None,
        location: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        updated_at: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        Input properties used for looking up and filtering Organization resources.

        :param pulumi.Input[_builtins.bool] ai_enabled: Whether AI features are enabled.
        :param pulumi.Input[_builtins.str] avatar: Avatar URL.
        :param pulumi.Input[_builtins.str] billing_email: Billing contact email.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the organization was created.
        :param pulumi.Input[_builtins.bool] deletion_protection: Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        :param pulumi.Input[_builtins.str] description: Organization description.
        :param pulumi.Input[_builtins.str] display_name: Display name shown in the UI.
        :param pulumi.Input[_builtins.bool] gateway_enabled: Whether gateway features are enabled.
        :param pulumi.Input[_builtins.str] github_handle: Organization GitHub handle.
        :param pulumi.Input[_builtins.bool] has_admin_panel: Whether the organization has access to the admin panel.
        :param pulumi.Input[_builtins.str] location: Organization location.
        :param pulumi.Input[_builtins.str] name: Organization name/slug.
        :param pulumi.Input[_builtins.str] updated_at: Timestamp when the organization was last updated.
        """
        if ai_enabled is not None:
            pulumi.set(__self__, "ai_enabled", ai_enabled)
        if avatar is not None:
            pulumi.set(__self__, "avatar", avatar)
        if billing_email is not None:
            pulumi.set(__self__, "billing_email", billing_email)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if deletion_protection is not None:
            pulumi.set(__self__, "deletion_protection", deletion_protection)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if gateway_enabled is not None:
            pulumi.set(__self__, "gateway_enabled", gateway_enabled)
        if github_handle is not None:
            pulumi.set(__self__, "github_handle", github_handle)
        if has_admin_panel is not None:
            pulumi.set(__self__, "has_admin_panel", has_admin_panel)
        if location is not None:
            pulumi.set(__self__, "location", location)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="aiEnabled")
    def ai_enabled(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether AI features are enabled.
        """
        return pulumi.get(self, "ai_enabled")

    @ai_enabled.setter
    def ai_enabled(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "ai_enabled", value)

    @_builtins.property
    @pulumi.getter
    def avatar(self) -> pulumi.Input[_builtins.str | None]:
        """
        Avatar URL.
        """
        return pulumi.get(self, "avatar")

    @avatar.setter
    def avatar(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "avatar", value)

    @_builtins.property
    @pulumi.getter(name="billingEmail")
    def billing_email(self) -> pulumi.Input[_builtins.str | None]:
        """
        Billing contact email.
        """
        return pulumi.get(self, "billing_email")

    @billing_email.setter
    def billing_email(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "billing_email", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[_builtins.str | None]:
        """
        Timestamp when the organization was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="deletionProtection")
    def deletion_protection(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        """
        return pulumi.get(self, "deletion_protection")

    @deletion_protection.setter
    def deletion_protection(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "deletion_protection", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Display name shown in the UI.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="gatewayEnabled")
    def gateway_enabled(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether gateway features are enabled.
        """
        return pulumi.get(self, "gateway_enabled")

    @gateway_enabled.setter
    def gateway_enabled(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "gateway_enabled", value)

    @_builtins.property
    @pulumi.getter(name="githubHandle")
    def github_handle(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization GitHub handle.
        """
        return pulumi.get(self, "github_handle")

    @github_handle.setter
    def github_handle(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "github_handle", value)

    @_builtins.property
    @pulumi.getter(name="hasAdminPanel")
    def has_admin_panel(self) -> pulumi.Input[_builtins.bool | None]:
        """
        Whether the organization has access to the admin panel.
        """
        return pulumi.get(self, "has_admin_panel")

    @has_admin_panel.setter
    def has_admin_panel(self, value: pulumi.Input[_builtins.bool | None]):
        pulumi.set(self, "has_admin_panel", value)

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization location.
        """
        return pulumi.get(self, "location")

    @location.setter
    def location(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "location", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization name/slug.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[_builtins.str | None]:
        """
        Timestamp when the organization was last updated.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("logfire:index/organization:Organization")
class Organization(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        avatar: pulumi.Input[_builtins.str | None] = None,
        billing_email: pulumi.Input[_builtins.str | None] = None,
        deletion_protection: pulumi.Input[_builtins.bool | None] = None,
        description: pulumi.Input[_builtins.str | None] = None,
        display_name: pulumi.Input[_builtins.str | None] = None,
        github_handle: pulumi.Input[_builtins.str | None] = None,
        location: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        """
        Create a Organization resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] avatar: Avatar URL.
        :param pulumi.Input[_builtins.str] billing_email: Billing contact email.
        :param pulumi.Input[_builtins.bool] deletion_protection: Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        :param pulumi.Input[_builtins.str] description: Organization description.
        :param pulumi.Input[_builtins.str] display_name: Display name shown in the UI.
        :param pulumi.Input[_builtins.str] github_handle: Organization GitHub handle.
        :param pulumi.Input[_builtins.str] location: Organization location.
        :param pulumi.Input[_builtins.str] name: Organization name/slug.
        """
        ...

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: OrganizationArgs | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Create a Organization resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param OrganizationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            OrganizationArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        avatar: pulumi.Input[_builtins.str | None] = None,
        billing_email: pulumi.Input[_builtins.str | None] = None,
        deletion_protection: pulumi.Input[_builtins.bool | None] = None,
        description: pulumi.Input[_builtins.str | None] = None,
        display_name: pulumi.Input[_builtins.str | None] = None,
        github_handle: pulumi.Input[_builtins.str | None] = None,
        location: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError("Expected resource options to be a ResourceOptions instance")
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = OrganizationArgs.__new__(OrganizationArgs)

            __props__.__dict__["avatar"] = avatar
            __props__.__dict__["billing_email"] = billing_email
            __props__.__dict__["deletion_protection"] = deletion_protection
            __props__.__dict__["description"] = description
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["github_handle"] = github_handle
            __props__.__dict__["location"] = location
            __props__.__dict__["name"] = name
            __props__.__dict__["ai_enabled"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["gateway_enabled"] = None
            __props__.__dict__["has_admin_panel"] = None
            __props__.__dict__["updated_at"] = None
        super().__init__(
            "logfire:index/organization:Organization",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        ai_enabled: pulumi.Input[_builtins.bool | None] = None,
        avatar: pulumi.Input[_builtins.str | None] = None,
        billing_email: pulumi.Input[_builtins.str | None] = None,
        created_at: pulumi.Input[_builtins.str | None] = None,
        deletion_protection: pulumi.Input[_builtins.bool | None] = None,
        description: pulumi.Input[_builtins.str | None] = None,
        display_name: pulumi.Input[_builtins.str | None] = None,
        gateway_enabled: pulumi.Input[_builtins.bool | None] = None,
        github_handle: pulumi.Input[_builtins.str | None] = None,
        has_admin_panel: pulumi.Input[_builtins.bool | None] = None,
        location: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        updated_at: pulumi.Input[_builtins.str | None] = None,
    ) -> Organization:
        """
        Get an existing Organization resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] ai_enabled: Whether AI features are enabled.
        :param pulumi.Input[_builtins.str] avatar: Avatar URL.
        :param pulumi.Input[_builtins.str] billing_email: Billing contact email.
        :param pulumi.Input[_builtins.str] created_at: Timestamp when the organization was created.
        :param pulumi.Input[_builtins.bool] deletion_protection: Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        :param pulumi.Input[_builtins.str] description: Organization description.
        :param pulumi.Input[_builtins.str] display_name: Display name shown in the UI.
        :param pulumi.Input[_builtins.bool] gateway_enabled: Whether gateway features are enabled.
        :param pulumi.Input[_builtins.str] github_handle: Organization GitHub handle.
        :param pulumi.Input[_builtins.bool] has_admin_panel: Whether the organization has access to the admin panel.
        :param pulumi.Input[_builtins.str] location: Organization location.
        :param pulumi.Input[_builtins.str] name: Organization name/slug.
        :param pulumi.Input[_builtins.str] updated_at: Timestamp when the organization was last updated.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrganizationState.__new__(_OrganizationState)

        __props__.__dict__["ai_enabled"] = ai_enabled
        __props__.__dict__["avatar"] = avatar
        __props__.__dict__["billing_email"] = billing_email
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["deletion_protection"] = deletion_protection
        __props__.__dict__["description"] = description
        __props__.__dict__["display_name"] = display_name
        __props__.__dict__["gateway_enabled"] = gateway_enabled
        __props__.__dict__["github_handle"] = github_handle
        __props__.__dict__["has_admin_panel"] = has_admin_panel
        __props__.__dict__["location"] = location
        __props__.__dict__["name"] = name
        __props__.__dict__["updated_at"] = updated_at
        return Organization(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="aiEnabled")
    def ai_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether AI features are enabled.
        """
        return pulumi.get(self, "ai_enabled")

    @_builtins.property
    @pulumi.getter
    def avatar(self) -> pulumi.Output[_builtins.str]:
        """
        Avatar URL.
        """
        return pulumi.get(self, "avatar")

    @_builtins.property
    @pulumi.getter(name="billingEmail")
    def billing_email(self) -> pulumi.Output[_builtins.str]:
        """
        Billing contact email.
        """
        return pulumi.get(self, "billing_email")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the organization was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="deletionProtection")
    def deletion_protection(self) -> pulumi.Output[_builtins.bool]:
        """
        Prevents accidental destroy when true (defaults to true). Set to false and apply before deleting this resource.
        """
        return pulumi.get(self, "deletion_protection")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Organization description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        Display name shown in the UI.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="gatewayEnabled")
    def gateway_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether gateway features are enabled.
        """
        return pulumi.get(self, "gateway_enabled")

    @_builtins.property
    @pulumi.getter(name="githubHandle")
    def github_handle(self) -> pulumi.Output[_builtins.str]:
        """
        Organization GitHub handle.
        """
        return pulumi.get(self, "github_handle")

    @_builtins.property
    @pulumi.getter(name="hasAdminPanel")
    def has_admin_panel(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the organization has access to the admin panel.
        """
        return pulumi.get(self, "has_admin_panel")

    @_builtins.property
    @pulumi.getter
    def location(self) -> pulumi.Output[_builtins.str]:
        """
        Organization location.
        """
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Organization name/slug.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the organization was last updated.
        """
        return pulumi.get(self, "updated_at")
