# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import Any

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass

__all__ = [
    "ChannelConfig",
]


@pulumi.output_type
class ChannelConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "authKey":
            suggest = "auth_key"
        elif key == "channelId":
            suggest = "channel_id"
        elif key == "includeAgentPrompt":
            suggest = "include_agent_prompt"
        elif key == "installId":
            suggest = "install_id"
        elif key == "routingKey":
            suggest = "routing_key"

        if suggest:
            pulumi.log.warn(
                f"Key '{key}' not found in ChannelConfig. Access the value via the '{suggest}' property getter instead."
            )

    def __getitem__(self, key: str) -> Any:
        ChannelConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default=None) -> Any:
        ChannelConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(
        __self__,
        *,
        type: _builtins.str,
        auth_key: _builtins.str | None = None,
        channel_id: _builtins.str | None = None,
        format: _builtins.str | None = None,
        include_agent_prompt: _builtins.bool | None = None,
        install_id: _builtins.str | None = None,
        region: _builtins.str | None = None,
        routing_key: _builtins.str | None = None,
        url: _builtins.str | None = None,
    ):
        """
        :param _builtins.str type: Channel type (<span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span>, <span pulumi-lang-nodejs="`opsgenie`" pulumi-lang-dotnet="`Opsgenie`" pulumi-lang-go="`opsgenie`" pulumi-lang-python="`opsgenie`" pulumi-lang-yaml="`opsgenie`" pulumi-lang-java="`opsgenie`" pulumi-lang-hcl="`opsgenie`">`opsgenie`</span>, <span pulumi-lang-nodejs="`pagerduty`" pulumi-lang-dotnet="`Pagerduty`" pulumi-lang-go="`pagerduty`" pulumi-lang-python="`pagerduty`" pulumi-lang-yaml="`pagerduty`" pulumi-lang-java="`pagerduty`" pulumi-lang-hcl="`pagerduty`">`pagerduty`</span>, or `slack-integration`).
        :param _builtins.str auth_key: Opsgenie API key.
        :param _builtins.str channel_id: Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        :param _builtins.str format: Webhook payload format.
        :param _builtins.bool include_agent_prompt: Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when omitted.
        :param _builtins.str install_id: ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
        :param _builtins.str region: PagerDuty account region (<span pulumi-lang-nodejs="`us`" pulumi-lang-dotnet="`Us`" pulumi-lang-go="`us`" pulumi-lang-python="`us`" pulumi-lang-yaml="`us`" pulumi-lang-java="`us`" pulumi-lang-hcl="`us`">`us`</span> or <span pulumi-lang-nodejs="`eu`" pulumi-lang-dotnet="`Eu`" pulumi-lang-go="`eu`" pulumi-lang-python="`eu`" pulumi-lang-yaml="`eu`" pulumi-lang-java="`eu`" pulumi-lang-hcl="`eu`">`eu`</span>). When omitted, Logfire uses the US Events API endpoint.
        :param _builtins.str routing_key: PagerDuty Events API v2 integration routing key.
        :param _builtins.str url: Webhook URL endpoint.
        """
        pulumi.set(__self__, "type", type)
        if auth_key is not None:
            pulumi.set(__self__, "auth_key", auth_key)
        if channel_id is not None:
            pulumi.set(__self__, "channel_id", channel_id)
        if format is not None:
            pulumi.set(__self__, "format", format)
        if include_agent_prompt is not None:
            pulumi.set(__self__, "include_agent_prompt", include_agent_prompt)
        if install_id is not None:
            pulumi.set(__self__, "install_id", install_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if routing_key is not None:
            pulumi.set(__self__, "routing_key", routing_key)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Channel type (<span pulumi-lang-nodejs="`webhook`" pulumi-lang-dotnet="`Webhook`" pulumi-lang-go="`webhook`" pulumi-lang-python="`webhook`" pulumi-lang-yaml="`webhook`" pulumi-lang-java="`webhook`" pulumi-lang-hcl="`webhook`">`webhook`</span>, <span pulumi-lang-nodejs="`opsgenie`" pulumi-lang-dotnet="`Opsgenie`" pulumi-lang-go="`opsgenie`" pulumi-lang-python="`opsgenie`" pulumi-lang-yaml="`opsgenie`" pulumi-lang-java="`opsgenie`" pulumi-lang-hcl="`opsgenie`">`opsgenie`</span>, <span pulumi-lang-nodejs="`pagerduty`" pulumi-lang-dotnet="`Pagerduty`" pulumi-lang-go="`pagerduty`" pulumi-lang-python="`pagerduty`" pulumi-lang-yaml="`pagerduty`" pulumi-lang-java="`pagerduty`" pulumi-lang-hcl="`pagerduty`">`pagerduty`</span>, or `slack-integration`).
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="authKey")
    def auth_key(self) -> _builtins.str | None:
        """
        Opsgenie API key.
        """
        return pulumi.get(self, "auth_key")

    @_builtins.property
    @pulumi.getter(name="channelId")
    def channel_id(self) -> _builtins.str | None:
        """
        Slack channel ID (for example `C0123456789`) the notifications are posted to. The Logfire Slack bot must already be a member of the channel.
        """
        return pulumi.get(self, "channel_id")

    @_builtins.property
    @pulumi.getter
    def format(self) -> _builtins.str | None:
        """
        Webhook payload format.
        """
        return pulumi.get(self, "format")

    @_builtins.property
    @pulumi.getter(name="includeAgentPrompt")
    def include_agent_prompt(self) -> _builtins.bool | None:
        """
        Whether Slack issue notifications include the "Ask your agent" MCP prompt line. Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span> when omitted.
        """
        return pulumi.get(self, "include_agent_prompt")

    @_builtins.property
    @pulumi.getter(name="installId")
    def install_id(self) -> _builtins.str | None:
        """
        ID of the organization's Slack App installation, created by connecting Slack in the Logfire UI (Organization Settings > Integrations). The installation must belong to the same organization and be active.
        """
        return pulumi.get(self, "install_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str | None:
        """
        PagerDuty account region (<span pulumi-lang-nodejs="`us`" pulumi-lang-dotnet="`Us`" pulumi-lang-go="`us`" pulumi-lang-python="`us`" pulumi-lang-yaml="`us`" pulumi-lang-java="`us`" pulumi-lang-hcl="`us`">`us`</span> or <span pulumi-lang-nodejs="`eu`" pulumi-lang-dotnet="`Eu`" pulumi-lang-go="`eu`" pulumi-lang-python="`eu`" pulumi-lang-yaml="`eu`" pulumi-lang-java="`eu`" pulumi-lang-hcl="`eu`">`eu`</span>). When omitted, Logfire uses the US Events API endpoint.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="routingKey")
    def routing_key(self) -> _builtins.str | None:
        """
        PagerDuty Events API v2 integration routing key.
        """
        return pulumi.get(self, "routing_key")

    @_builtins.property
    @pulumi.getter
    def url(self) -> _builtins.str | None:
        """
        Webhook URL endpoint.
        """
        return pulumi.get(self, "url")
