# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = ["Project", "ProjectArgs"]


@pulumi.input_type
class ProjectArgs:
    def __init__(
        __self__,
        *,
        description: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        visibility: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        The set of arguments for constructing a Project resource.

        :param pulumi.Input[_builtins.str] description: Project description.
        :param pulumi.Input[_builtins.str] name: Project name/slug. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] visibility: Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if visibility is not None:
            pulumi.set(__self__, "visibility", visibility)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project name/slug. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def visibility(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        return pulumi.get(self, "visibility")

    @visibility.setter
    def visibility(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "visibility", value)


@pulumi.input_type
class _ProjectState:
    def __init__(
        __self__,
        *,
        description: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        organization: pulumi.Input[_builtins.str | None] = None,
        visibility: pulumi.Input[_builtins.str | None] = None,
    ):
        """
        Input properties used for looking up and filtering Project resources.

        :param pulumi.Input[_builtins.str] description: Project description.
        :param pulumi.Input[_builtins.str] name: Project name/slug. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] organization: Organization name. Computed from the API and cannot be set.
        :param pulumi.Input[_builtins.str] visibility: Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if visibility is not None:
            pulumi.set(__self__, "visibility", visibility)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project description.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project name/slug. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Input[_builtins.str | None]:
        """
        Organization name. Computed from the API and cannot be set.
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def visibility(self) -> pulumi.Input[_builtins.str | None]:
        """
        Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        return pulumi.get(self, "visibility")

    @visibility.setter
    def visibility(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "visibility", value)


@pulumi.type_token("logfire:index/project:Project")
class Project(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        description: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        visibility: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        """
        Create a Project resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Project description.
        :param pulumi.Input[_builtins.str] name: Project name/slug. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] visibility: Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        ...

    @overload
    def __init__(
        __self__,
        resource_name: str,
        args: ProjectArgs | None = None,
        opts: pulumi.ResourceOptions | None = None,
    ):
        """
        Create a Project resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProjectArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            ProjectArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        description: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        visibility: pulumi.Input[_builtins.str | None] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError("Expected resource options to be a ResourceOptions instance")
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = ProjectArgs.__new__(ProjectArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            __props__.__dict__["visibility"] = visibility
            __props__.__dict__["organization"] = None
        super().__init__(
            "logfire:index/project:Project",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        description: pulumi.Input[_builtins.str | None] = None,
        name: pulumi.Input[_builtins.str | None] = None,
        organization: pulumi.Input[_builtins.str | None] = None,
        visibility: pulumi.Input[_builtins.str | None] = None,
    ) -> Project:
        """
        Get an existing Project resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Project description.
        :param pulumi.Input[_builtins.str] name: Project name/slug. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] organization: Organization name. Computed from the API and cannot be set.
        :param pulumi.Input[_builtins.str] visibility: Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectState.__new__(_ProjectState)

        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["organization"] = organization
        __props__.__dict__["visibility"] = visibility
        return Project(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str | None]:
        """
        Project description.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Project name/slug. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization name. Computed from the API and cannot be set.
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def visibility(self) -> pulumi.Output[_builtins.str]:
        """
        Project visibility (<span pulumi-lang-nodejs="`public`" pulumi-lang-dotnet="`Public`" pulumi-lang-go="`public`" pulumi-lang-python="`public`" pulumi-lang-yaml="`public`" pulumi-lang-java="`public`" pulumi-lang-hcl="`public`">`public`</span> or <span pulumi-lang-nodejs="`private`" pulumi-lang-dotnet="`Private`" pulumi-lang-go="`private`" pulumi-lang-python="`private`" pulumi-lang-yaml="`private`" pulumi-lang-java="`private`" pulumi-lang-hcl="`private`">`private`</span>).
        """
        return pulumi.get(self, "visibility")
