# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from collections.abc import Mapping, Sequence
from typing import overload

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities, outputs
from ._inputs import *

__all__ = ["Bucket", "BucketArgs"]


@pulumi.input_type
class BucketArgs:
    def __init__(
        __self__,
        *,
        bucket_name: pulumi.Input[_builtins.str],
        bucket_type: pulumi.Input[_builtins.str],
        b2_bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_info: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        cors_rules: pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None] = None,
        default_server_side_encryption: pulumi.Input[
            BucketDefaultServerSideEncryptionArgs | None
        ] = None,
        file_lock_configurations: pulumi.Input[
            Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None
        ] = None,
        lifecycle_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None
        ] = None,
    ):
        """
        The set of arguments for constructing a Bucket resource.

        :param pulumi.Input[_builtins.str] bucket_name: The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] bucket_type: The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] bucket_info: User-defined information to be stored with the bucket.
        :param pulumi.Input[Sequence[pulumi.Input['BucketCorsRuleArgs']]] cors_rules: The initial list of CORS rules for this bucket.
        :param pulumi.Input['BucketDefaultServerSideEncryptionArgs'] default_server_side_encryption: The default server-side encryption settings for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input['BucketFileLockConfigurationArgs']]] file_lock_configurations: File lock enabled flag, and default retention settings.
        :param pulumi.Input[Sequence[pulumi.Input['BucketLifecycleRuleArgs']]] lifecycle_rules: The initial list of lifecycle rules for this bucket.
        """
        pulumi.set(__self__, "bucket_name", bucket_name)
        pulumi.set(__self__, "bucket_type", bucket_type)
        if b2_bucket_id is not None:
            pulumi.set(__self__, "b2_bucket_id", b2_bucket_id)
        if bucket_info is not None:
            pulumi.set(__self__, "bucket_info", bucket_info)
        if cors_rules is not None:
            pulumi.set(__self__, "cors_rules", cors_rules)
        if default_server_side_encryption is not None:
            pulumi.set(__self__, "default_server_side_encryption", default_server_side_encryption)
        if file_lock_configurations is not None:
            pulumi.set(__self__, "file_lock_configurations", file_lock_configurations)
        if lifecycle_rules is not None:
            pulumi.set(__self__, "lifecycle_rules", lifecycle_rules)

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_name")

    @bucket_name.setter
    def bucket_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "bucket_name", value)

    @_builtins.property
    @pulumi.getter(name="bucketType")
    def bucket_type(self) -> pulumi.Input[_builtins.str]:
        """
        The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        """
        return pulumi.get(self, "bucket_type")

    @bucket_type.setter
    def bucket_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "bucket_type", value)

    @_builtins.property
    @pulumi.getter(name="b2BucketId")
    def b2_bucket_id(self) -> pulumi.Input[_builtins.str | None]:
        return pulumi.get(self, "b2_bucket_id")

    @b2_bucket_id.setter
    def b2_bucket_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "b2_bucket_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketInfo")
    def bucket_info(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        User-defined information to be stored with the bucket.
        """
        return pulumi.get(self, "bucket_info")

    @bucket_info.setter
    def bucket_info(self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]):
        pulumi.set(self, "bucket_info", value)

    @_builtins.property
    @pulumi.getter(name="corsRules")
    def cors_rules(self) -> pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None]:
        """
        The initial list of CORS rules for this bucket.
        """
        return pulumi.get(self, "cors_rules")

    @cors_rules.setter
    def cors_rules(self, value: pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None]):
        pulumi.set(self, "cors_rules", value)

    @_builtins.property
    @pulumi.getter(name="defaultServerSideEncryption")
    def default_server_side_encryption(
        self,
    ) -> pulumi.Input[BucketDefaultServerSideEncryptionArgs | None]:
        """
        The default server-side encryption settings for this bucket.
        """
        return pulumi.get(self, "default_server_side_encryption")

    @default_server_side_encryption.setter
    def default_server_side_encryption(
        self, value: pulumi.Input[BucketDefaultServerSideEncryptionArgs | None]
    ):
        pulumi.set(self, "default_server_side_encryption", value)

    @_builtins.property
    @pulumi.getter(name="fileLockConfigurations")
    def file_lock_configurations(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None]:
        """
        File lock enabled flag, and default retention settings.
        """
        return pulumi.get(self, "file_lock_configurations")

    @file_lock_configurations.setter
    def file_lock_configurations(
        self, value: pulumi.Input[Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None]
    ):
        pulumi.set(self, "file_lock_configurations", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleRules")
    def lifecycle_rules(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None]:
        """
        The initial list of lifecycle rules for this bucket.
        """
        return pulumi.get(self, "lifecycle_rules")

    @lifecycle_rules.setter
    def lifecycle_rules(
        self, value: pulumi.Input[Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None]
    ):
        pulumi.set(self, "lifecycle_rules", value)


@pulumi.input_type
class _BucketState:
    def __init__(
        __self__,
        *,
        account_id: pulumi.Input[_builtins.str | None] = None,
        b2_bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_info: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        bucket_name: pulumi.Input[_builtins.str | None] = None,
        bucket_type: pulumi.Input[_builtins.str | None] = None,
        cors_rules: pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None] = None,
        default_server_side_encryption: pulumi.Input[
            BucketDefaultServerSideEncryptionArgs | None
        ] = None,
        file_lock_configurations: pulumi.Input[
            Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None
        ] = None,
        lifecycle_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None
        ] = None,
        options: pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None] = None,
        revision: pulumi.Input[_builtins.float | None] = None,
    ):
        """
        Input properties used for looking up and filtering Bucket resources.

        :param pulumi.Input[_builtins.str] account_id: Account ID that the bucket belongs to.
        :param pulumi.Input[_builtins.str] bucket_id: The ID of the bucket.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] bucket_info: User-defined information to be stored with the bucket.
        :param pulumi.Input[_builtins.str] bucket_name: The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] bucket_type: The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        :param pulumi.Input[Sequence[pulumi.Input['BucketCorsRuleArgs']]] cors_rules: The initial list of CORS rules for this bucket.
        :param pulumi.Input['BucketDefaultServerSideEncryptionArgs'] default_server_side_encryption: The default server-side encryption settings for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input['BucketFileLockConfigurationArgs']]] file_lock_configurations: File lock enabled flag, and default retention settings.
        :param pulumi.Input[Sequence[pulumi.Input['BucketLifecycleRuleArgs']]] lifecycle_rules: The initial list of lifecycle rules for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] options: List of bucket options.
        :param pulumi.Input[_builtins.float] revision: Bucket revision.
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if b2_bucket_id is not None:
            pulumi.set(__self__, "b2_bucket_id", b2_bucket_id)
        if bucket_id is not None:
            pulumi.set(__self__, "bucket_id", bucket_id)
        if bucket_info is not None:
            pulumi.set(__self__, "bucket_info", bucket_info)
        if bucket_name is not None:
            pulumi.set(__self__, "bucket_name", bucket_name)
        if bucket_type is not None:
            pulumi.set(__self__, "bucket_type", bucket_type)
        if cors_rules is not None:
            pulumi.set(__self__, "cors_rules", cors_rules)
        if default_server_side_encryption is not None:
            pulumi.set(__self__, "default_server_side_encryption", default_server_side_encryption)
        if file_lock_configurations is not None:
            pulumi.set(__self__, "file_lock_configurations", file_lock_configurations)
        if lifecycle_rules is not None:
            pulumi.set(__self__, "lifecycle_rules", lifecycle_rules)
        if options is not None:
            pulumi.set(__self__, "options", options)
        if revision is not None:
            pulumi.set(__self__, "revision", revision)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        Account ID that the bucket belongs to.
        """
        return pulumi.get(self, "account_id")

    @account_id.setter
    def account_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "account_id", value)

    @_builtins.property
    @pulumi.getter(name="b2BucketId")
    def b2_bucket_id(self) -> pulumi.Input[_builtins.str | None]:
        return pulumi.get(self, "b2_bucket_id")

    @b2_bucket_id.setter
    def b2_bucket_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "b2_bucket_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> pulumi.Input[_builtins.str | None]:
        """
        The ID of the bucket.
        """
        return pulumi.get(self, "bucket_id")

    @bucket_id.setter
    def bucket_id(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "bucket_id", value)

    @_builtins.property
    @pulumi.getter(name="bucketInfo")
    def bucket_info(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]:
        """
        User-defined information to be stored with the bucket.
        """
        return pulumi.get(self, "bucket_info")

    @bucket_info.setter
    def bucket_info(self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None]):
        pulumi.set(self, "bucket_info", value)

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Input[_builtins.str | None]:
        """
        The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_name")

    @bucket_name.setter
    def bucket_name(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "bucket_name", value)

    @_builtins.property
    @pulumi.getter(name="bucketType")
    def bucket_type(self) -> pulumi.Input[_builtins.str | None]:
        """
        The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        """
        return pulumi.get(self, "bucket_type")

    @bucket_type.setter
    def bucket_type(self, value: pulumi.Input[_builtins.str | None]):
        pulumi.set(self, "bucket_type", value)

    @_builtins.property
    @pulumi.getter(name="corsRules")
    def cors_rules(self) -> pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None]:
        """
        The initial list of CORS rules for this bucket.
        """
        return pulumi.get(self, "cors_rules")

    @cors_rules.setter
    def cors_rules(self, value: pulumi.Input[Sequence[pulumi.Input[BucketCorsRuleArgs]] | None]):
        pulumi.set(self, "cors_rules", value)

    @_builtins.property
    @pulumi.getter(name="defaultServerSideEncryption")
    def default_server_side_encryption(
        self,
    ) -> pulumi.Input[BucketDefaultServerSideEncryptionArgs | None]:
        """
        The default server-side encryption settings for this bucket.
        """
        return pulumi.get(self, "default_server_side_encryption")

    @default_server_side_encryption.setter
    def default_server_side_encryption(
        self, value: pulumi.Input[BucketDefaultServerSideEncryptionArgs | None]
    ):
        pulumi.set(self, "default_server_side_encryption", value)

    @_builtins.property
    @pulumi.getter(name="fileLockConfigurations")
    def file_lock_configurations(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None]:
        """
        File lock enabled flag, and default retention settings.
        """
        return pulumi.get(self, "file_lock_configurations")

    @file_lock_configurations.setter
    def file_lock_configurations(
        self, value: pulumi.Input[Sequence[pulumi.Input[BucketFileLockConfigurationArgs]] | None]
    ):
        pulumi.set(self, "file_lock_configurations", value)

    @_builtins.property
    @pulumi.getter(name="lifecycleRules")
    def lifecycle_rules(
        self,
    ) -> pulumi.Input[Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None]:
        """
        The initial list of lifecycle rules for this bucket.
        """
        return pulumi.get(self, "lifecycle_rules")

    @lifecycle_rules.setter
    def lifecycle_rules(
        self, value: pulumi.Input[Sequence[pulumi.Input[BucketLifecycleRuleArgs]] | None]
    ):
        pulumi.set(self, "lifecycle_rules", value)

    @_builtins.property
    @pulumi.getter
    def options(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]:
        """
        List of bucket options.
        """
        return pulumi.get(self, "options")

    @options.setter
    def options(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None]):
        pulumi.set(self, "options", value)

    @_builtins.property
    @pulumi.getter
    def revision(self) -> pulumi.Input[_builtins.float | None]:
        """
        Bucket revision.
        """
        return pulumi.get(self, "revision")

    @revision.setter
    def revision(self, value: pulumi.Input[_builtins.float | None]):
        pulumi.set(self, "revision", value)


@pulumi.type_token("b2:index/bucket:Bucket")
class Bucket(pulumi.CustomResource):
    @overload
    def __init__(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        b2_bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_info: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        bucket_name: pulumi.Input[_builtins.str | None] = None,
        bucket_type: pulumi.Input[_builtins.str | None] = None,
        cors_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketCorsRuleArgs | BucketCorsRuleArgsDict]] | None
        ] = None,
        default_server_side_encryption: pulumi.Input[
            BucketDefaultServerSideEncryptionArgs | BucketDefaultServerSideEncryptionArgsDict | None
        ] = None,
        file_lock_configurations: pulumi.Input[
            Sequence[
                pulumi.Input[BucketFileLockConfigurationArgs | BucketFileLockConfigurationArgsDict]
            ]
            | None
        ] = None,
        lifecycle_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketLifecycleRuleArgs | BucketLifecycleRuleArgsDict]] | None
        ] = None,
        __props__=None,
    ):
        """
        Create a Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] bucket_info: User-defined information to be stored with the bucket.
        :param pulumi.Input[_builtins.str] bucket_name: The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] bucket_type: The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketCorsRuleArgs', 'BucketCorsRuleArgsDict']]]] cors_rules: The initial list of CORS rules for this bucket.
        :param pulumi.Input[Union['BucketDefaultServerSideEncryptionArgs', 'BucketDefaultServerSideEncryptionArgsDict']] default_server_side_encryption: The default server-side encryption settings for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketFileLockConfigurationArgs', 'BucketFileLockConfigurationArgsDict']]]] file_lock_configurations: File lock enabled flag, and default retention settings.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketLifecycleRuleArgs', 'BucketLifecycleRuleArgsDict']]]] lifecycle_rules: The initial list of lifecycle rules for this bucket.
        """
        ...

    @overload
    def __init__(
        __self__, resource_name: str, args: BucketArgs, opts: pulumi.ResourceOptions | None = None
    ):
        """
        Create a Bucket resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param BucketArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...

    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(
            BucketArgs, pulumi.ResourceOptions, *args, **kwargs
        )
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(
        __self__,
        resource_name: str,
        opts: pulumi.ResourceOptions | None = None,
        b2_bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_info: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        bucket_name: pulumi.Input[_builtins.str | None] = None,
        bucket_type: pulumi.Input[_builtins.str | None] = None,
        cors_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketCorsRuleArgs | BucketCorsRuleArgsDict]] | None
        ] = None,
        default_server_side_encryption: pulumi.Input[
            BucketDefaultServerSideEncryptionArgs | BucketDefaultServerSideEncryptionArgsDict | None
        ] = None,
        file_lock_configurations: pulumi.Input[
            Sequence[
                pulumi.Input[BucketFileLockConfigurationArgs | BucketFileLockConfigurationArgsDict]
            ]
            | None
        ] = None,
        lifecycle_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketLifecycleRuleArgs | BucketLifecycleRuleArgsDict]] | None
        ] = None,
        __props__=None,
    ):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError("Expected resource options to be a ResourceOptions instance")
        if opts.id is None:
            if __props__ is not None:
                raise TypeError(
                    "__props__ is only valid when passed in combination with a valid opts.id to get an existing resource"
                )
            __props__ = BucketArgs.__new__(BucketArgs)

            __props__.__dict__["b2_bucket_id"] = b2_bucket_id
            __props__.__dict__["bucket_info"] = bucket_info
            if bucket_name is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_name'")
            __props__.__dict__["bucket_name"] = bucket_name
            if bucket_type is None and not opts.urn:
                raise TypeError("Missing required property 'bucket_type'")
            __props__.__dict__["bucket_type"] = bucket_type
            __props__.__dict__["cors_rules"] = cors_rules
            __props__.__dict__["default_server_side_encryption"] = default_server_side_encryption
            __props__.__dict__["file_lock_configurations"] = file_lock_configurations
            __props__.__dict__["lifecycle_rules"] = lifecycle_rules
            __props__.__dict__["account_id"] = None
            __props__.__dict__["bucket_id"] = None
            __props__.__dict__["options"] = None
            __props__.__dict__["revision"] = None
        super().__init__(
            "b2:index/bucket:Bucket",
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package(),
        )

    @staticmethod
    def get(
        resource_name: str,
        id: pulumi.Input[str],
        opts: pulumi.ResourceOptions | None = None,
        account_id: pulumi.Input[_builtins.str | None] = None,
        b2_bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_id: pulumi.Input[_builtins.str | None] = None,
        bucket_info: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]] | None] = None,
        bucket_name: pulumi.Input[_builtins.str | None] = None,
        bucket_type: pulumi.Input[_builtins.str | None] = None,
        cors_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketCorsRuleArgs | BucketCorsRuleArgsDict]] | None
        ] = None,
        default_server_side_encryption: pulumi.Input[
            BucketDefaultServerSideEncryptionArgs | BucketDefaultServerSideEncryptionArgsDict | None
        ] = None,
        file_lock_configurations: pulumi.Input[
            Sequence[
                pulumi.Input[BucketFileLockConfigurationArgs | BucketFileLockConfigurationArgsDict]
            ]
            | None
        ] = None,
        lifecycle_rules: pulumi.Input[
            Sequence[pulumi.Input[BucketLifecycleRuleArgs | BucketLifecycleRuleArgsDict]] | None
        ] = None,
        options: pulumi.Input[Sequence[pulumi.Input[_builtins.str]] | None] = None,
        revision: pulumi.Input[_builtins.float | None] = None,
    ) -> Bucket:
        """
        Get an existing Bucket resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_id: Account ID that the bucket belongs to.
        :param pulumi.Input[_builtins.str] bucket_id: The ID of the bucket.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] bucket_info: User-defined information to be stored with the bucket.
        :param pulumi.Input[_builtins.str] bucket_name: The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        :param pulumi.Input[_builtins.str] bucket_type: The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketCorsRuleArgs', 'BucketCorsRuleArgsDict']]]] cors_rules: The initial list of CORS rules for this bucket.
        :param pulumi.Input[Union['BucketDefaultServerSideEncryptionArgs', 'BucketDefaultServerSideEncryptionArgsDict']] default_server_side_encryption: The default server-side encryption settings for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketFileLockConfigurationArgs', 'BucketFileLockConfigurationArgsDict']]]] file_lock_configurations: File lock enabled flag, and default retention settings.
        :param pulumi.Input[Sequence[pulumi.Input[Union['BucketLifecycleRuleArgs', 'BucketLifecycleRuleArgsDict']]]] lifecycle_rules: The initial list of lifecycle rules for this bucket.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] options: List of bucket options.
        :param pulumi.Input[_builtins.float] revision: Bucket revision.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _BucketState.__new__(_BucketState)

        __props__.__dict__["account_id"] = account_id
        __props__.__dict__["b2_bucket_id"] = b2_bucket_id
        __props__.__dict__["bucket_id"] = bucket_id
        __props__.__dict__["bucket_info"] = bucket_info
        __props__.__dict__["bucket_name"] = bucket_name
        __props__.__dict__["bucket_type"] = bucket_type
        __props__.__dict__["cors_rules"] = cors_rules
        __props__.__dict__["default_server_side_encryption"] = default_server_side_encryption
        __props__.__dict__["file_lock_configurations"] = file_lock_configurations
        __props__.__dict__["lifecycle_rules"] = lifecycle_rules
        __props__.__dict__["options"] = options
        __props__.__dict__["revision"] = revision
        return Bucket(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accountId")
    def account_id(self) -> pulumi.Output[_builtins.str]:
        """
        Account ID that the bucket belongs to.
        """
        return pulumi.get(self, "account_id")

    @_builtins.property
    @pulumi.getter(name="b2BucketId")
    def b2_bucket_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "b2_bucket_id")

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the bucket.
        """
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter(name="bucketInfo")
    def bucket_info(self) -> pulumi.Output[Mapping[str, _builtins.str] | None]:
        """
        User-defined information to be stored with the bucket.
        """
        return pulumi.get(self, "bucket_info")

    @_builtins.property
    @pulumi.getter(name="bucketName")
    def bucket_name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the bucket. **Modifying this attribute will force creation of a new resource.**
        """
        return pulumi.get(self, "bucket_name")

    @_builtins.property
    @pulumi.getter(name="bucketType")
    def bucket_type(self) -> pulumi.Output[_builtins.str]:
        """
        The bucket type. Either 'allPublic', meaning that files in this bucket can be downloaded by anybody, or 'allPrivate'.
        """
        return pulumi.get(self, "bucket_type")

    @_builtins.property
    @pulumi.getter(name="corsRules")
    def cors_rules(self) -> pulumi.Output[Sequence[outputs.BucketCorsRule] | None]:
        """
        The initial list of CORS rules for this bucket.
        """
        return pulumi.get(self, "cors_rules")

    @_builtins.property
    @pulumi.getter(name="defaultServerSideEncryption")
    def default_server_side_encryption(
        self,
    ) -> pulumi.Output[outputs.BucketDefaultServerSideEncryption | None]:
        """
        The default server-side encryption settings for this bucket.
        """
        return pulumi.get(self, "default_server_side_encryption")

    @_builtins.property
    @pulumi.getter(name="fileLockConfigurations")
    def file_lock_configurations(
        self,
    ) -> pulumi.Output[Sequence[outputs.BucketFileLockConfiguration] | None]:
        """
        File lock enabled flag, and default retention settings.
        """
        return pulumi.get(self, "file_lock_configurations")

    @_builtins.property
    @pulumi.getter(name="lifecycleRules")
    def lifecycle_rules(self) -> pulumi.Output[Sequence[outputs.BucketLifecycleRule] | None]:
        """
        The initial list of lifecycle rules for this bucket.
        """
        return pulumi.get(self, "lifecycle_rules")

    @_builtins.property
    @pulumi.getter
    def options(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        List of bucket options.
        """
        return pulumi.get(self, "options")

    @_builtins.property
    @pulumi.getter
    def revision(self) -> pulumi.Output[_builtins.float]:
        """
        Bucket revision.
        """
        return pulumi.get(self, "revision")
