# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys
from collections.abc import Sequence

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities, outputs

__all__ = [
    "AwaitableGetBucketNotificationRulesResult",
    "GetBucketNotificationRulesResult",
    "get_bucket_notification_rules",
    "get_bucket_notification_rules_output",
]


@pulumi.output_type
class GetBucketNotificationRulesResult:
    """
    A collection of values returned by getBucketNotificationRules.
    """

    def __init__(__self__, bucket_id=None, id=None, notification_rules=None):
        if bucket_id and not isinstance(bucket_id, str):
            raise TypeError("Expected argument 'bucket_id' to be a str")
        pulumi.set(__self__, "bucket_id", bucket_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if notification_rules and not isinstance(notification_rules, list):
            raise TypeError("Expected argument 'notification_rules' to be a list")
        pulumi.set(__self__, "notification_rules", notification_rules)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> _builtins.str:
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="notificationRules")
    def notification_rules(
        self,
    ) -> Sequence[outputs.GetBucketNotificationRulesNotificationRuleResult]:
        return pulumi.get(self, "notification_rules")


class AwaitableGetBucketNotificationRulesResult(GetBucketNotificationRulesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketNotificationRulesResult(
            bucket_id=self.bucket_id, id=self.id, notification_rules=self.notification_rules
        )


def get_bucket_notification_rules(
    bucket_id: _builtins.str | None = None,
    id: _builtins.str | None = None,
    opts: pulumi.InvokeOptions | None = None,
) -> AwaitableGetBucketNotificationRulesResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__["bucketId"] = bucket_id
    __args__["id"] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke(
        "b2:index/getBucketNotificationRules:getBucketNotificationRules",
        __args__,
        opts=opts,
        typ=GetBucketNotificationRulesResult,
        package_ref=_utilities.get_package(),
    ).value

    return AwaitableGetBucketNotificationRulesResult(
        bucket_id=pulumi.get(__ret__, "bucket_id"),
        id=pulumi.get(__ret__, "id"),
        notification_rules=pulumi.get(__ret__, "notification_rules"),
    )


def get_bucket_notification_rules_output(
    bucket_id: pulumi.Input[_builtins.str | None] = None,
    id: pulumi.Input[_builtins.str | None] = None,
    opts: pulumi.InvokeOptions | pulumi.InvokeOutputOptions | None = None,
) -> pulumi.Output[GetBucketNotificationRulesResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__["bucketId"] = bucket_id
    __args__["id"] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output(
        "b2:index/getBucketNotificationRules:getBucketNotificationRules",
        __args__,
        opts=opts,
        typ=GetBucketNotificationRulesResult,
        package_ref=_utilities.get_package(),
    )
    return __ret__.apply(
        lambda __response__: GetBucketNotificationRulesResult(
            bucket_id=pulumi.get(__response__, "bucket_id"),
            id=pulumi.get(__response__, "id"),
            notification_rules=pulumi.get(__response__, "notification_rules"),
        )
    )
