# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import sys

import pulumi
import pulumi.runtime

if sys.version_info >= (3, 11):
    pass
else:
    pass
from . import _utilities

__all__ = [
    "AwaitableGetBucketFileSignedUrlResult",
    "GetBucketFileSignedUrlResult",
    "get_bucket_file_signed_url",
    "get_bucket_file_signed_url_output",
]


@pulumi.output_type
class GetBucketFileSignedUrlResult:
    """
    A collection of values returned by getBucketFileSignedUrl.
    """

    def __init__(__self__, bucket_id=None, duration=None, file_name=None, id=None, signed_url=None):
        if bucket_id and not isinstance(bucket_id, str):
            raise TypeError("Expected argument 'bucket_id' to be a str")
        pulumi.set(__self__, "bucket_id", bucket_id)
        if duration and not isinstance(duration, float):
            raise TypeError("Expected argument 'duration' to be a float")
        pulumi.set(__self__, "duration", duration)
        if file_name and not isinstance(file_name, str):
            raise TypeError("Expected argument 'file_name' to be a str")
        pulumi.set(__self__, "file_name", file_name)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if signed_url and not isinstance(signed_url, str):
            raise TypeError("Expected argument 'signed_url' to be a str")
        pulumi.set(__self__, "signed_url", signed_url)

    @_builtins.property
    @pulumi.getter(name="bucketId")
    def bucket_id(self) -> _builtins.str:
        return pulumi.get(self, "bucket_id")

    @_builtins.property
    @pulumi.getter
    def duration(self) -> _builtins.float | None:
        return pulumi.get(self, "duration")

    @_builtins.property
    @pulumi.getter(name="fileName")
    def file_name(self) -> _builtins.str:
        return pulumi.get(self, "file_name")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="signedUrl")
    def signed_url(self) -> _builtins.str:
        return pulumi.get(self, "signed_url")


class AwaitableGetBucketFileSignedUrlResult(GetBucketFileSignedUrlResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetBucketFileSignedUrlResult(
            bucket_id=self.bucket_id,
            duration=self.duration,
            file_name=self.file_name,
            id=self.id,
            signed_url=self.signed_url,
        )


def get_bucket_file_signed_url(
    bucket_id: _builtins.str | None = None,
    duration: _builtins.float | None = None,
    file_name: _builtins.str | None = None,
    id: _builtins.str | None = None,
    opts: pulumi.InvokeOptions | None = None,
) -> AwaitableGetBucketFileSignedUrlResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__["bucketId"] = bucket_id
    __args__["duration"] = duration
    __args__["fileName"] = file_name
    __args__["id"] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke(
        "b2:index/getBucketFileSignedUrl:getBucketFileSignedUrl",
        __args__,
        opts=opts,
        typ=GetBucketFileSignedUrlResult,
        package_ref=_utilities.get_package(),
    ).value

    return AwaitableGetBucketFileSignedUrlResult(
        bucket_id=pulumi.get(__ret__, "bucket_id"),
        duration=pulumi.get(__ret__, "duration"),
        file_name=pulumi.get(__ret__, "file_name"),
        id=pulumi.get(__ret__, "id"),
        signed_url=pulumi.get(__ret__, "signed_url"),
    )


def get_bucket_file_signed_url_output(
    bucket_id: pulumi.Input[_builtins.str | None] = None,
    duration: pulumi.Input[_builtins.float | None] = None,
    file_name: pulumi.Input[_builtins.str | None] = None,
    id: pulumi.Input[_builtins.str | None] = None,
    opts: pulumi.InvokeOptions | pulumi.InvokeOutputOptions | None = None,
) -> pulumi.Output[GetBucketFileSignedUrlResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__["bucketId"] = bucket_id
    __args__["duration"] = duration
    __args__["fileName"] = file_name
    __args__["id"] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output(
        "b2:index/getBucketFileSignedUrl:getBucketFileSignedUrl",
        __args__,
        opts=opts,
        typ=GetBucketFileSignedUrlResult,
        package_ref=_utilities.get_package(),
    )
    return __ret__.apply(
        lambda __response__: GetBucketFileSignedUrlResult(
            bucket_id=pulumi.get(__response__, "bucket_id"),
            duration=pulumi.get(__response__, "duration"),
            file_name=pulumi.get(__response__, "file_name"),
            id=pulumi.get(__response__, "id"),
            signed_url=pulumi.get(__response__, "signed_url"),
        )
    )
