from logging.config import fileConfig
from typing import Any

from alembic import context
from sqlalchemy import create_engine
from sqlalchemy.engine import Connection, make_url

from old_news.config import get_settings
from old_news.db.base import Base

# Importing the models is what populates Base.metadata; without it every
# autogenerated revision would helpfully drop the entire schema.
import old_news.db.models  # noqa: F401  isort:skip

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# No host or credential is baked into alembic.ini — same rule as everywhere else.
# A caller may set the URL explicitly; the test suite does, to pin migrations to
# its container rather than whatever .env happens to name.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", get_settings().database.migration_url)


# type_ and parent_names are spelled with Literal keys in Alembic's stubs; Any
# keeps this readable without restating them.
def include_name(name: str | None, type_: Any, parent_names: Any) -> bool:
    """Procrastinate owns its own tables and migrates them itself.

    Without this, every autogenerated revision opens with a dozen `drop_table`
    calls for a schema Alembic never created.
    """
    if name is None:
        return True
    # alembic_utils qualifies its entities with a schema; tables arrive bare.
    return not name.rpartition(".")[2].startswith("procrastinate_")


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_name=include_name,
        compare_type=True,
        compare_server_default=True,
    )


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


def _sync_url(url: str) -> str:
    """Callers hand over whatever the app runs on, which may name an async driver."""
    # `str()` on a URL masks the password, which then fails to authenticate.
    parsed = make_url(url).set(drivername="postgresql+psycopg")
    return parsed.render_as_string(hide_password=False)


def run_migrations_online() -> None:
    engine = create_engine(_sync_url(config.get_main_option("sqlalchemy.url", "")))
    with engine.connect() as connection:
        _run(connection)
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
