import asyncio
from logging.config import fileConfig
from typing import Any

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from old_news.config import get_settings
from old_news.db.base import Base

# Importing the models is what populates Base.metadata; without it every
# autogenerated revision would helpfully drop the entire schema.
import old_news.db.models  # noqa: F401  isort:skip

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# No host or credential is baked into alembic.ini — same rule as everywhere else.
# A caller may set the URL explicitly; the test suite does, to pin migrations to
# its container rather than whatever .env happens to name.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", get_settings().database.sqlalchemy_url)


# type_ and parent_names are spelled with Literal keys in Alembic's stubs; Any
# keeps this readable without restating them.
def include_name(name: str | None, type_: Any, parent_names: Any) -> bool:
    """Procrastinate owns its own tables and migrates them itself.

    Without this, every autogenerated revision opens with a dozen `drop_table`
    calls for a schema Alembic never created.
    """
    if type_ == "table" and name is not None:
        return not name.startswith("procrastinate_")
    return True


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_name=include_name,
        compare_type=True,
        compare_server_default=True,
    )


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_run)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
