# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import sys

if sys.version_info >= (3, 11):
    pass
else:
    pass

apiKey: str | None
"""
Bearer token. If omitted, the LOGFIRE_API_KEY environment variable is used.
"""

baseUrl: str | None
"""
Base URL for the Logfire API. If omitted, the provider uses LOGFIRE_BASE_URL or infers the SaaS endpoint from the<span pulumi-lang-nodejs=" apiKey " pulumi-lang-dotnet=" ApiKey " pulumi-lang-go=" apiKey " pulumi-lang-python=" api_key " pulumi-lang-yaml=" apiKey " pulumi-lang-java=" apiKey " pulumi-lang-hcl=" api_key "> apiKey </span>region. Self-hosted customers should set this explicitly.
"""

customHeaders: str | None
"""
Additional HTTP headers to include on every Logfire API request. Intended for proxy, gateway, or edge authentication. Provider-managed headers cannot be overridden.
"""
